### ISSUE TITLE
Add image answer format to capture image in a question step

### ISSUE THREAD

**Issue by YuanZhu-apple** [ResearchKit/ResearchKit#1]
Some researchers are interested in developing medical research apps that require access to the camera and save images in high resolution.
* Create an image answer format class which could have a few attributes like:  resolution, flash light, and output format. 
* Design a question step UI interface to capture an image and display it to the user. 
* `ORKFileResult` should be used to return the image file reference.

**Comment by imanabu** [comment]
We are definitely interested in participating in this implementation. We have been developing a medical grade photography application called BodyMapSnap. It captures not just the picture, but also other meta data including the body location where the photo was taken from.

**Comment by jwe-apple** [comment]
In ResearchKit the collection of other metadata would happen either by incorporating the image answer format in a form item on a form step, or by incorporating an image answer format in a question step within a larger task which might incorporate those other questions.

We would love to have you contribute an implementation. The first step is probably an engineering mockup of how you propose it would look in both the form and question step scenarios, and then an API proposal for the answer format itself.

**Comment by brucehappy** [comment]
I've been looking at this as well, and should be able to upload a few screenshots of a mockup for form and question steps very soon.

**Comment by imanabu** [comment]
Sorry about apparent inactivity, but we have been working with other NIH researcher to see what would best way to address this. There are some medical specific questions we can ask the participants and also how the photography is integrated, and from our standpoint, what will happen to the images, where they are stored. I look forward to see the mockup as well.

**Comment by jwe-apple** [comment]
Assigned to @brucehappy as further progress sounds imminent.

**Comment by brucehappy** [comment]
In a form step, I've shown a few approaches to the image capture answer.  The first has the text being a section header, and the latter two have the text being within the cell, on the left, as in other cell types (I added the "INLINE CONTROLS" section to separate them from the first one).  I'm showing a few different sizes of the control in this form, as well.  I thought that the size of the control could be something set in the answer format, and then perhaps based on that size the form cell could decide dynamically whether to use a section header for the text, or include it in the cell.  I've also included a question step example too.  (The first two pictures below are of the same screen, it is just scrolled down in the second picture)

Clicking on the blue bordered image capture control transitions to another view controller.  This view controller serves as the screen to launch the camera or photo library from, as well as a preview page once a picture has been chosen from the library, or taken with the camera.  This view controller could also serve as a place for instructions on how to properly take the picture.  I'm essentially showing the final step right now ("Take a new photo, or choose one from your library"), but there could be instructions prior to this screen, including animations and text that you might force them to flip through until they get to the last screen where they can finally choose or take a photo.  I did not include any pictures of this possible set of instructions below.

Pressing the Photo Library button shows the standard "Moments", "Camera Roll", etc, and I did not include a picture of that below.  I thought that including the ability to use the Photo Library might be appropriate if the user took the photo outside the ResearchKit app for some reason.  Perhaps they took it with another camera, or another app, or did it before the survey due to the photo needing to be taken at a specific time that was not the same as the time the survey was answered.

Pressing the camera icon brings up the camera.  I know that @YuanZhu-apple mentioned the idea of having flash as an attribute of the answer format, but here, I've let the normal camera controls be shown and changeable by the user, including flash.

After taking or choosing a picture, you get to confirm it by hitting Done or Cancel.  If you hit Done, then the control that launched the view controller is updated with the selected photo, replacing the camera icon that was there previously.  Obviously, within the control we could crop the picture, or keep the aspect ratio correct, etc, but for this (relatively) quick proof, I've let the button scale the image to fit.  I've included an image of this process being done with the large form control example, but it works exactly the same with the smaller ones.

FYI, these pictures were all taken on my iPhone 5.

I look forward to your thoughts.
 
![form_01](https://cloud.githubusercontent.com/assets/5296062/7270871/64ed908c-e8ad-11e4-9c95-3755644dd622.png)
![form_02](https://cloud.githubusercontent.com/assets/5296062/7270872/64f188cc-e8ad-11e4-9b98-c67a215354ac.png)
![question_01](https://cloud.githubusercontent.com/assets/5296062/7270875/64fbcdc8-e8ad-11e4-889e-bed0f313a15d.png)
![form_camera_button_pressed](https://cloud.githubusercontent.com/assets/5296062/7270873/64f4cec4-e8ad-11e4-8910-ce3cb79d24dc.png)
![camera_button_pressed](https://cloud.githubusercontent.com/assets/5296062/7270870/64dfa54e-e8ad-11e4-8f01-a4e6f44ba27d.png)
![shutter_button_pressed](https://cloud.githubusercontent.com/assets/5296062/7270876/64ffade4-e8ad-11e4-8bff-0cb06f4855c8.png)
![use_photo_button_pressed](https://cloud.githubusercontent.com/assets/5296062/7270877/65030386-e8ad-11e4-9791-b1c8a0e64986.png)
![form_updated_with_picture](https://cloud.githubusercontent.com/assets/5296062/7270874/64f6fae6-e8ad-11e4-9b07-53ea8c2f381d.png)

**Comment by jwe-apple** [comment]
Thanks for this, I'm circulating for feedback.

**Comment by jwe-apple** [comment]
@brucehappy Could we do another iteration on this? We feel the forms version feels a bit too much like engineering UI. The question step version is a bit clunky too. We wonder if integrating the camera directly into the task navigation flow might be preferable, and simply document that it would be normal to preface with an instruction step.

Other things to give thought to include annotations or instructions displayed overlaid on the camera view finder; and how to handle image editing.

To be fair this is exactly where we would start have started too, but we want to push this to be a little bit better!

**Comment by brucehappy** [comment]
Thanks for the feedback.  Ok, so the idea is to make the image capture an ORKStep subclass, correct?  Seems like a good idea.

Overlays are definitely something that makes sense to do in order to guide them to take the picture properly.

As for editing, I'm having trouble thinking of a reason that applying filters might make sense, but, certainly I could see where cropping or rotation might be helpful to assist them in making the picture meet the requirements laid out in the instructions...but I wonder whether rotating and cropping would really be needed if the overlay provided enough guidance on taking the picture.  Allowing participants to annotate the pictures, however, seems like something that could be very helpful to researchers, with the participant circling areas of interest, for example.

Another area of interest is verification.  I'm not sure what kind of verification should, or could, be applied to the captured image to ensure it meets the requirements of the researchers.  Seems to me that we would need a specialized image processing library to implement a verification process, and even then, its likely only basic checks would be sufficiently reliable.

I'll put together some new mockups based on these comments.  Thanks.

**Comment by jwe-apple** [comment]
I'd leave the question of whether it's an ORKQuestionStep subclass or an ORKStep subclass for later. Let's define the interaction we want first.

Yes, I'd leave off verification for now - can always be added later for particular requirements.

For editing I'd focus on cropping; other editing tasks are probably secondary but those are some good ideas.

**Comment by brucehappy** [comment]
Here's another shot at this.  I didn't include the cropping step as I wanted to get confirmation this was the right direction.  Apologies for the verbosity.

![joined](https://cloud.githubusercontent.com/assets/5296062/7424594/5264d05e-ef71-11e4-847c-831aaf20c839.jpg)

**Comment by DanKeen** [comment]
Thanks - that's a great direction. I think this is much closer to what we were envisioning.

**Comment by jwe-apple** [comment]
Yep, this is great. This demo sequence would be great to have, too in one of the test/demo apps too. Let's get this done, and we can look at editing as a follow-on step.

**Comment by brucehappy** [comment]
Glad to hear I'm on the right track.  I'll start working on getting this code into shape and removing all the twine and tape thats holding it together right now :wink: .

**Comment by jwe-apple** [comment]
@brucehappy What's your state on this? If you've got something which is close but don't have time for cleanup, we'd still like to have it and can help with getting it ready to ingest.

**Comment by brucehappy** [comment]
I've been delayed with another project.  I'll have a PR for this today.

**Comment by jwe-apple** [comment]
No problem!

**Comment by jwe-apple** [comment]
Completed.

**Comment by sergiomeza** [comment]
The "Take a new photo, or choose one from your library" answer format has been implemented?, if so, how can i use it? thanks
