### ISSUE TITLE
Customised message in alert controller in ORKAnswerFormat.integerAnswerFormat

### ISSUE THREAD

**Issue by nasim-ahmed** [ResearchKit/ResearchKit#1018]
I have set a minimum value and a maximum value for the answer I am expecting. If a user types in a value beyond the range, an alert view controller is displayed, telling the value is invalid. What can I do to customise the message shown in the alert.

**Comment by kelseydedoshka-apple** [comment]
@nasim-ahmed - at the moment the framework doesn't support customization of the message displayed when an invalid value is entered. However this is a great idea for us to consider moving forward.

You can however modify the framework if necessary to provide a customized string. At the moment you can look at the localizedInvalidValueStringWithAnswerString function in ORKAnswerFormat.m and you will notice the localization string RANGE_ALERT_MESSAGE_ABOVE_MAXIMUM (and similar for minimum) that are being displayed when a value become invalid. You could replace those strings with you custom material. 

If this doesn't fit your need please reach back out here.

**Comment by kelseydedoshka-apple** [comment]
@nasim-ahmed - just wanted to check in here to see if this helped resolve your issue?

**Comment by simon-apple** [comment]
Thank you for raising this issue and for your interest in ResearchKit! Since we haven’t received any follow-up or additional details, we’re going to close this issue for now to keep things organized. If you're still encountering this problem or need help, please feel free to reopen the issue or create a new one with updated information. We’re happy to assist when possible!
