### ISSUE TITLE
ResearchKit:How to display the custom strings in Y-Axis in ORKLineCharts

### ISSUE THREAD

**Issue by hemanthkorada** [ResearchKit/ResearchKit#1039]
By Default i am able to display numbers in the Y-Axis , how could i display Labels with strings in Y-Axis to meet my requirement. Screen short attached.

Actually i am able to do by adding native labels in the Y-Axis, But not matching with the exact plotting point and the Y-Axis label in a same horizontal line.

![img_0557](https://user-images.githubusercontent.com/16497240/33433418-791a0628-d601-11e7-86dc-47f4dab8eb47.PNG)

**Comment by kelseydedoshka-apple** [comment]
@hemanthkorada - most of the labeling work for the y-axis is done in the RK framework itself so for more control over this I would suggest looking to either edit or extend the framework itself. You can look at the graph views in the charts folder of the framework for where to start. 

On the other hand you could add reference lines via the existing API to the charts to help mitigate the lack of labels. This might be a much simpler approach.

Hopefully this is enough to help you get started!

**Comment by simon-apple** [comment]
Thanks for the feedback! The charts feature has since been removed from ResearchKit, but [Swift Charts](https://developer.apple.com/documentation/charts) can be used instead. Please feel free to open a new issue if you have any other requests or questions. Thank you again for your support of ResearchKit!
