### ISSUE TITLE
Adding highlighted reference lines on x/y axes 

### ISSUE THREAD

**Issue by boscojwho** [ResearchKit/ResearchKit#1094]
Has anyone attempted to add a highlighted reference line inside ORKLineChartGraphView similar to the one in the screenshot below?  Unfortunately, `showsHorizontalReferenceLines` and `showsVerticalReferenceLines` isn't enough for our use case.

<img width="762" alt="screen shot 2018-03-19 at 4 52 10 pm" src="https://user-images.githubusercontent.com/2549615/37628284-0d62ca1a-2b96-11e8-803f-80d8954b1682.png">

Using only existing public API, we would have to manually add a line as a subview, and somehow convert data point values into UIView drawing coordinates using `minimumValue` and `maximumValue`. Obviously, this data point to drawing coordinates conversion function doesn't exist (unless it's somewhere inside the internals).

Much appreciated if anyone has a working solution using only current public APIs, or has managed to use the internal APIs to get this working.

**Comment by simon-apple** [comment]
Thanks for the feedback! The charts feature has since been removed from ResearchKit, but [Swift Charts](https://developer.apple.com/documentation/charts) can be used instead. Please feel free to open a new issue if you have any other requests or questions. Thank you again for your support of ResearchKit!
