### ISSUE TITLE
Customize number of reference lines draw on x/y axes

### ISSUE THREAD

**Issue by boscojwho** [ResearchKit/ResearchKit#1095]
Any tips if we wanted to customize `ORKGraphChartView` to draw more reference lines between data points?

Currently, the behaviour is binary: either show or hide. When the data range is small in terms of whole numbers (e.g. 36 - 42), we'd prefer the chart to draw more lines at every 0.10 of a data point, for example.

**Comment by srinathtm-apple** [comment]
@boscojwho isn't this customizable by returning the appropriate value in numberOfDivisionsInXAxisForGraphChartView ?

If you notice that your range is small, provide a higher value for numberOfDivisions in the data source delegate callback.

**Comment by srinathtm-apple** [comment]
@boscojwho are you referring to the case where you want to draw reference lines at every 0.10 of a data point even though actual value doesn't exist? I think that will require some changes to the implementation itself, not sure if that can be done using just the existing APIs. 

Maybe you can interpolate some values into your data ?

**Comment by simon-apple** [comment]
Thanks for the feedback! The charts feature has since been removed from ResearchKit, but [Swift Charts](https://developer.apple.com/documentation/charts) can be used instead. Please feel free to open a new issue if you have any other requests or questions. Thank you again for your support of ResearchKit!
