### ISSUE TITLE
Questions about displaying scores

### ISSUE THREAD

**Issue by windenchanter** [ResearchKit/ResearchKit#1096]
I am trying to display scores for the result from different tasks. 

The discrete graph looks like an ok option to me (I think I can just reload it after I have calculated the value), however, I am wondering if the following can be done, or has been done.:
1. Adding x-axis labels --- the default labels are numerical, I'd like to replace them with text labels. 
2. Add a label to the markers or change the size of the marker --- the data point marker is too small. It would also be nice to add a legend or a label to reflect the numerical value of the marker. 
3. Drawing a horizontal dashed reference line across the y-axis. 

Alternatively, I'd like to display the scores in a table. I do have the scores calculated, but I am having trouble to update anything displayed under the "Scores" tab. I am new to programming so any pointers on how to do this would be appreciated.  

Also, it is possible (or easy) to display an HTML file for showing scores (like the HTML custom consent form)?

**Comment by rsanchezsaez** [comment]
Hi again @windenchanter,

I'm happy to try and help in this instance as well (I'm not sure if this issue is still valid, or if you decided to go with `ORKPieChartView` instead).

---

You can definitely reload a discrete graph chart after you have calculated its data source values, just call `reloadData` discrete graph chart on the class.

----

1. You can display string values for the x-axis labels, using the `-graphChartView:titleForXAxisAtPointIndex:` method on the `ORKGraphChartViewDataSource`. Let me know if this doesn't work for you and why.
2. What do you mean by marker? Could you provide more information and/or a detailed graphical mockup?
3. This wouldn't be to complicated by modifying the ORKGraphChartView drawing code and adding a new delegate method to display an horizontal reference line. Let me know if this is of interest to you and I can look at implementing it.

---

Regarding displaying the scores in a table, you may achieve this by creating your own custom view to display (completely separate from `ResearchKit` charts). For that you'd need to create your own labels and layout them appropriately. You'd need to learn more about laying `UIKit` views out to achieve this.

---

Regarding HTML, a Pull Request was merged a while back introducing the possibility of adding a `ORKWebViewStep` with your own HTML code:
- https://github.com/ResearchKit/ResearchKit/pull/1030

Let me know if all this helps if you need further assistance.

**Comment by windenchanter** [comment]
Hi @rsanchezsaez 

Thank you!

I have decided to use the pie chart to display the score. But the information you provide here is also valuable, as I may still use the discrete graph for other purposes of summarizing the score. 

For marker size, see attached image for an example of a marker. 
![image](https://user-images.githubusercontent.com/22673319/38113495-6af05d0e-3362-11e8-87ad-1e88e6c0426c.png)
I am used to plotting using Matlab and R, they provide ways of manipulating the marker, as size and shape of the marker were used to display multiple conditions on the same graph. 

I think I am getting close the desired outcome with the pie charts so I may not need an HTML to manage the contents displayed for now.

**Comment by simon-apple** [comment]
Thanks for the feedback! The charts feature has since been removed from ResearchKit, but [Swift Charts](https://developer.apple.com/documentation/charts) can be used instead. Please feel free to open a new issue if you have any other requests or questions. Thank you again for your support of ResearchKit!
