### ISSUE TITLE
Customizing pie chart's legend

### ISSUE THREAD

**Issue by windenchanter** [ResearchKit/ResearchKit#1097]
![image](https://user-images.githubusercontent.com/22673319/37855093-228482a6-2eb3-11e8-833f-c99f97901700.png)
I set the alpha level to 0 for item 2 so that item 2 disappears, but it pushes the legend of Item1 to the left. I am trying to remove the Item1 legend at the bottom or move it to a different location. 

Also, I wonder if there's a way to fixate the legend showing percentage value at one location. Its location changes depending on the percentage value.

**Comment by rsanchezsaez** [comment]
Hi @windenchanter,

It seems that the visual changes that you are requesting will need code changes on the `ORKPieChartView` class and its related component classes. I'm the one who adapted these classes  from the *Apple*-provided but less flexible `AppCore` project for a more general usage on `ResearchKit`. I'm happy to help you making changes to achieve your desired results.

I'm not sure I understand your requirements. Could you specify in more detail what you need? In your first paragraph, you seem to imply that you want to completely disable the legend for `Item 2`, and that this should cause *Item 1* to be centered in the legend, rather than pushed to the left. Is that right? If this is so, I could add a new `ORKPieChartViewDataSource` method asking for which segments you want to display, returning a `BOOL` and this would fix your layout issues. This is relatively easy.

However, you also seem to ask to remove *Item 1* as well. Note that if don't implement the `-pieChartView:titleForSegmentAtIndex:` method in your `ORKPieChartViewDataSource`, the legend won't be displayed at all. Also note that moving the legend to an arbitrary position is quite difficult based on the current code, as the legend view is a constrained view that is currently always below the main pie chart view. Where is your desired position? Could you provide more details or a specific mockup of what you need?

As for your second paragraph, I think I don't fully understand what you want to achieve. Do you want to move the percentage label to a different location? Note that this is not part of the legend, this a percentage label attached to the main pie chart view. If you want to hide those, you can do so by using the `BOOL showsPercentageLabels` property on `ORKPieChartView`. If this is not what you want, what do you want achieve exactly?

Let me know your clarifications, and let's see what we can do.

**Comment by windenchanter** [comment]
Hi, @rsanchezsaez 
Thank you for getting back on this issue. I think changing the label location is sufficient for what I need to achieve. I can get a new ORKPieChartViewDataSource method to return a bool, how can I apply this to disable the legend for specified Segment? 

I have added a function inside to update the contents depending on the score:
`    func update_data(title : String, score : Int){
        self.segments = [
            Segment(title: title, value: Float(score), color: UIColor(red: 220/225, green: 20/255, blue: 20/225, alpha: 1)),
            Segment(title: "", value: 100 - Float(score) , color: UIColor(red: 100/225, green: 60/255, blue: 217/225, alpha: 0)),
        ]
    }`

As you can see I have two segments, the second segment is showing 100- current score, so that the pie can be used to display a percentage score.  That is why I don't want the legend to display the second segment at all. 

With regard to the second question:
See the two images attached. Depending on the percentage, the location of this percentage label moved. What I want to achieve is to make it appear at the same location (e.g., where the 0% is on the buttom image) regardless what the percentage is. 
![image](https://user-images.githubusercontent.com/22673319/38113070-2384f6f6-3361-11e8-87a7-a505e71ed963.png)
![image](https://user-images.githubusercontent.com/22673319/38113088-2dc8c21e-3361-11e8-9848-b6e59dec085b.png)

**Comment by rsanchezsaez** [comment]
Hi @windenchanter,

I have implemented a part of your request in https://github.com/ResearchKit/ResearchKit/pull/1107

Now you can skip legend labels for certain sections by returning `nil` on the *data source*'s `-pieChartView:titleForSegmentAtIndex:` method, and the rest of labels will be laid out appropriately.

Is this enough for your purposes? If it is not, I can try to implement further modifications, but be aware that modifying the position of the floating percentage label next to the pie chart segments is more difficult. Please let me know your thoughts.

**Comment by windenchanter** [comment]
@rsanchezsaez 
Thank you!
After updating the code, the legends disappeared altogether. I am not sure whether I made a mistake or something is going on in the updated code caused this. Or perhaps there was a way to turn off the legend and I accidentally turned them off. 

The location of the percentage display is not a major concern, so there's no need to change it. I am wondering if there's a way to change the percentage label's color to a different color from the pie chart?

**Comment by windenchanter** [comment]
@rsanchezsaez 
In my case, the title disappeared at the storyboard. I think they are supposed to be initialized with a title in the ORKPieChartView.m file.

`- (instancetype)init {
    self = [super init];
    if (self) {
        ORKIBPieChartViewDataSourceSegment *segment1 = [ORKIBPieChartViewDataSourceSegment new];
        segment1.value = 10.0;
        segment1.title = @"Title 1";
        segment1.color = [UIColor colorWithRed:217.0/225 green:217.0/255 blue:217.0/225 alpha:1];
        
        ORKIBPieChartViewDataSourceSegment *segment2 = [ORKIBPieChartViewDataSourceSegment new];
        segment2.value = 25.0;
        segment2.title = @"Title 2";
        segment2.color = [UIColor colorWithRed:142.0/255 green:142.0/255 blue:147.0/255 alpha:1];
        
        ORKIBPieChartViewDataSourceSegment *segment3 = [ORKIBPieChartViewDataSourceSegment new];
        segment3.value = 45.0;
        segment3.title = @"Title 3";
        segment3.color = [UIColor colorWithRed:244.0/225 green:190.0/255 blue:74.0/225 alpha:1];
        
        _segments = @[segment1, segment2, segment3];
    }
    return self;
}`

![image](https://user-images.githubusercontent.com/22673319/38437178-e30971f4-3993-11e8-80dd-3b67f309f1c4.png)

**Comment by simon-apple** [comment]
Thanks for the feedback! The charts feature has since been removed from ResearchKit, but [Swift Charts](https://developer.apple.com/documentation/charts) can be used instead. Please feel free to open a new issue if you have any other requests or questions. Thank you again for your support of ResearchKit!
