### ISSUE TITLE
Task UI in README Uses Outdated UI

### ISSUE THREAD

**Issue by DreamingInBinary** [ResearchKit/ResearchKit#1276]
Currently, the image is housed in the Wiki but it uses the old style-UI:

![HelloWorld](https://user-images.githubusercontent.com/5566805/58337064-9a006280-7e0a-11e9-9786-d4a2fbce4ad0.png)

When it should reflect this:
![newUI](https://user-images.githubusercontent.com/5566805/58337079-a08eda00-7e0a-11e9-82c2-d9d2e39fa356.png)

I don't _think_ I could send a PR for this since the image is hosted in the wiki which I don't have access to, apologies if I overlooked something there.

**Comment by simon-apple** [comment]
Thanks for bringing this up! This issue has since been addressed in ResearchKit. We recommend upgrading to the latest release, which includes this fix along with many improvements and new features. If you encounter any issues after upgrading, feel free to open a new issue. Thanks for your support and for contributing to ResearchKit!
