### ISSUE TITLE
Documentation mentions `yAxisLabelFactors` but its not exposed in the Framework

### ISSUE THREAD

**Issue by frogg** [ResearchKit/ResearchKit#1284]
I've spotted the property `yAxisLabelFactors ` in http://researchkit.org/docs/Classes/ORKGraphChartView.html#//api/name/yAxisLabelFactors which looks like an interesting API.

However, in the framework itself this property is not exposed (so I guess I cannot use it for now?).

It would be great to clarify that in the documentation and/or to implement this addition to the class itself.

**Comment by simon-apple** [comment]
Thanks for the feedback! The charts feature has since been removed from ResearchKit, but [Swift Charts](https://developer.apple.com/documentation/charts) can be used instead. Please feel free to open a new issue if you have any other requests or questions. Thank you again for your support of ResearchKit!
