### ISSUE TITLE
Getting Ready for Dark Mode

### ISSUE THREAD

**Issue by ZaidSA** [ResearchKit/ResearchKit#1297]
Hello There,

As we know [Dark Mode](https://developer.apple.com/news/?id=0829019a) is coming to iOS this September.

What are ResearchKit's plans to support it? How ResearchKit developers can take advantage of Dark Mode?

**Comment by srinathtm-apple** [comment]
Hey @ZaidSA , we are currently working on adding support for dark mode throughout ResearchKit. You should see these changes starting to trickle down in a few weeks.

**Comment by tmprk** [comment]
Any updates on this?

**Comment by countsnap** [comment]
when can we expect to see dark mode support? iOS 13 has been out for a while now

**Comment by srinathtm-apple** [comment]
Dark mode support for most of our core classes is available on master branch right now!

**Comment by countsnap** [comment]
@srinathtm-apple thanks for quick the reply - any plans to back port dark mode support to ResearchKit 1.5.3?

**Comment by simon-apple** [comment]
Thanks for bringing this up! This issue has since been addressed in ResearchKit. We recommend upgrading to the latest release, which includes this fix along with many improvements and new features. If you encounter any issues after upgrading, feel free to open a new issue. Thanks for your support and for contributing to ResearchKit!
