### ISSUE TITLE
Why do you use UIPageViewController inside UINavigationController?

### ISSUE THREAD

**Issue by nskboy** [ResearchKit/ResearchKit#133]
I noticed that `ORKTaskViewController` uses following hierarchy of view controllers:

    ORKTaskViewController
      UINavigationController
        UIPageViewController
          ORKStepViewController

I wonder why don't just simplify the code and throw away page view controller? You can push step view controllers in navigation controller in a similar way.

**Comment by jwe-apple** [comment]
We definitely don't want navigation controller, because that maintains a stack of view controllers. We don't want all that state. We want two or at most three view controllers loaded at a time, and usually only want one (the visible one).

Admittedly, UIPageViewController isn't ideal for this purpose - the fact we're still using it is historical. It would be preferable to use a custom container view controller instead of UIPageViewController, to give more accurate and customizable control over transitions, and perhaps we'll change that at some point - no API depends on it.

**Comment by jwe-apple** [comment]
@nskboy Let me know if that answered your question!

**Comment by nskboy** [comment]
Thanks! Now I get it.
