### ISSUE TITLE
Improved Survey Skip Logic

### ISSUE THREAD

**Issue by hershman** [ResearchKit/ResearchKit#138]
For the Asthma Health app, we ran into a couple limitations in implementing the daily survey.  There are two specific features related to survey skip logic we'd love in order to improve the experience for our users:

1. __Cross Survey Skip Logic__: We're using the daily survey to asses if users took their controller medication.  Users who aren't prescribed controller medication shouldn't see these questions.  A question from the medication survey could be used to detect these users, but it's not clear how we can link the medication response in the context of the daily survey.

2. __Multi-Response Skip Logic__: In the daily survey we have a question about symptoms during the day and another about night. If the user answers yes to either of these, we would like to ask a follow-up question, but we're not sure how to access the responses to multiple questions when defining a skip rule.

**Comment by rsanchezsaez** [comment]
Regarding *Multi-Response Skip Logic*, that will be possible when we finish the *ordered task with navigation rules* implementation ([issue #86](https://github.com/ResearchKit/ResearchKit/issues/86)). We're working on it already.

On *Cross Survey Skip Logic*, I'm not sure if *ResearchKit* should handle this. When you finish a survey, *ResearchKit* provides you with the results, and the app is responsible for handling and/or storing them. *ResearchKit* doesn't relate independently run tasks. Maybe this part could be an *AppCore* feature request? (@jwe-apple: please correct me if I'm wrong).

**Comment by jwe-apple** [comment]
@rsanchezsaez Cross Survey Skip Logic sounds like something we should think about including in the navigation rules task already in progress. Two ways it could be achieved:

1) Providing an override point where a subclass could use a parameter to control.

2) Providing a way to inject extra identifiers into the namespace for predicates, so that a predicate can operate against an additional result set, perhaps from another task entirely.

I think I prefer the latter but an experiment in writing an example is probably merited.

**Comment by rsanchezsaez** [comment]
I'll see what I can do.

**Comment by jwe-apple** [comment]
I believe both have been addressed by PR #151
