### ISSUE TITLE
Loading text choices from asynchronous source

### ISSUE THREAD

**Issue by nskboy** [ResearchKit/ResearchKit#141]
I'm experimenting with loading array of `ORKTextChoice` from the network resource and displaying it with default `ORKQuestionStepViewController`. I know I can provide custom view controller for that but I think it should be supported out of the box.

Currently I can't figure out how to fit this feature in established ResearchKit architecture. Have you thought of this? Could you provide any ideas how API would change to support that?

**Comment by jwe-apple** [comment]
Ah, so you want to use `ORKQuestionStepViewController` without a task view controller?

I don't believe any API change is required. You need to create an `ORKQuestionStep` with an appropriate `ORKAnswerFormat` subclass containing your text choices. Then instantiate the question step view controller, set the step, and present it. You will want to provide a delegate to catch button taps / changes in the result.

**Comment by jwe-apple** [comment]
Note this isn't the normal way to use `ORKQuestionStepViewController` - the normal way is by putting your step in a task, and using an `ORKTaskViewController` to manage the presentation process. Why do you want to do it this way?

**Comment by nskboy** [comment]
Well, actually, I was so inspired by core API with simple and elegant entities like task, steps, answers and results so I started thinking how to generalize the API in order to make general purpose setup wizard for an application. And currently I'm stuck on how would new API look when you have setup wizard (aka `ORKTask`) with two steps:

1. Enter valid server address step. This can be done with form like answer.
2. Use server address from step 1 to fetch data and present it like single or multiple text choice question. BTW, sharing user input with next steps is done via `-[id<ORKTaskViewControllerDelegate> taskViewController:didChangeResult:]` or there is other way of doing that?

**Comment by nskboy** [comment]
Also, I would like to thank you @jwe-apple for fast responses (considering time zone difference 😀). It is pleasure for me to read your relevant answers for my questions.

**Comment by jwe-apple** [comment]
You're right - if you had a server address entry step, then you would pass the entered address back up to your task view controller's delegate by changing the result. And it would come back via the delegate method as you identified.

I would then follow that with a custom "loading" step (I would subclass `ORKActiveStep`, and `ORKActiveStepViewController` similar to the countdown, but add the loading logic). Your loading step view controller would be responsible for triggering the fetch and updating the backing store for your task (you would customize the step view controller in the `willPresentStepViewController` delegate callback). When the fetch completes, you would change the result of the "loading" step, which would trigger the task view controller to ask the `ORKTask` for the next step (in case it has changed). Since you've loaded the rest of the task from the network it would indeed have changed.

So you'd have several components you'd need:
* Something implementing `ORKTask` which owns an `ORKOrderedTask` containing the first few steps, and has a concept of dynamically loaded follow-on steps
* A fairly generic `ORKLoadingStep` / `ORKLoadingStepViewController`
* The networking part, probably with a cache
* A parser to convert the input content into steps to supplement the initial task
* You'd probably want to include server-side configuration of where to send the results, and immediate result uploading with a follow-on loading step.

Sounds like an interesting direction to explore.

**Comment by jwe-apple** [comment]
The clever part would be if you could manage to do the dynamic loading of steps while avoiding doing anything in the task view controller's delegate, which is really the "application" rather than the framework. If you could do this completely in an `ORKTask` implementation, purely by responding to `stepAfterStep:withResult:` calls and a suitable `ORKLoadingStepViewController` and `ORKLoadingStep` implementation (the loading step and its VC would need a reference back to the task and would need to know some details of the task), then application code could use this `ORKTask` implementation fairly transparently.

**Comment by nskboy** [comment]
Wow, I haven't consider separating fetch from presenting :) Your approach suits best for my needs.

Last detail to clarify: Is there any particular reasons for separating fetching & presenting beside classic "separation of concerns"? Before talking to you I had something like `-[id<ORKTextChoiceRepository> fetchTextChoicesWithCompletion:]` for `ORKQuestionStepViewController`. This approach however requires more code to add into pretty heavy `ORKQuestionStepViewController` forcing it to track state of the repo and change to public API of `ORKStepViewController` since it being initialized with `ORKStep` instead of `ORKTextChoiceRepository`.

**Comment by nskboy** [comment]
> If you could do this completely in an `ORKTask` implementation, purely by responding to `stepAfterStep:withResult:` calls and a suitable `ORKLoadingStepViewController` and `ORKLoadingStep` implementation (the loading step and its VC would need a reference back to the task and would need to know some details of the task), then application code could use this `ORKTask` implementation fairly transparently.

I like the idea of feeding `ORKTask` to `ORKTaskViewController` but I don't like hard coding dependencies between steps.

What do you think of adding the ability to specify other step result dependencies to the `ORKStep` instance like this: `[someTask setDependsOnResultsOfStepsWithIdentifiers:@[ @"step1", @"step2" ]]`? 

Given this change one can update the implementation of `-[ORKTaskViewController setManagedResult:forKey:]` with the call like this `[step provideResult:result fromStepId:stepIdentifier]`?

**Comment by jwe-apple** [comment]
Main reason for separating fetching and presenting is that the underlying data model of ResearchKit assumes that steps, once presented, are static (do not change). You shouldn't present a step view controller without having the step first.

There's some work in progress to produce an ordered task with navigation rules, where the next step after a step is determined by applying predicates to the results.

I don't think you'd be hard coding the relationship between steps; it's just that those steps would be "special" within your managed task implementation.

Steps shouldn't know anything about the other steps in the task. A provideResult:fromStepId: would imply the step knew something about other steps.

**Comment by nskboy** [comment]
You mean pull request #151, right? Does it contain more or less stable public API I can rely on?

**Comment by jwe-apple** [comment]
No, it's not stable yet. API review starts today, you're welcome to provide feedback.

**Comment by nskboy** [comment]
I'd love to!

**Comment by nskboy** [comment]
> There's some work in progress to produce an ordered task with navigation rules, where the next step after a step is determined by applying predicates to the results.

I just reviewed the code and I don't get how navigation rules might be relevant for step dependencies.

> I don't think you'd be hard coding the relationship between steps; it's just that those steps would be "special" within your managed task implementation.

Again, I don't get your idea. Could you please provide raw implementation of this or explain a bit more?

**Comment by rsanchezsaez** [comment]
Maybe have a look at `ORKTest`'s *Step Navigation Task* example? Looking at the corresponding code in `MainViewController` is a quick way to see the API in use.

**Comment by nskboy** [comment]
Yes, I see navigation rule API in use. But how does navigation rule relate to passing step result from previous step to the current (eg. I need to pass first step result to the second and third steps)?

**Comment by jwe-apple** [comment]
Steps themselves should be treated as immutable and should not depend on other steps. Instead do this in your implementation of `ORKTask`, which is responsible for providing next/previous steps and can retain some state in order to do so.
