### ISSUE TITLE
Upgrade documentation to DocC when available for objective-c

### ISSUE THREAD

**Issue by SwiftNativeDeveloper** [ResearchKit/ResearchKit#1467]
DocC documentation is wonderful on the web and especially within Xcode.

It would be great to see the current documentation migrate to DocC when it becomes available to Objective-C code or when/if ResearchKit gets ported to Swift.

Additionally, more documentation using articles and code samples using the new DocC capabilities are highly desired to elevate the current documentation to the next level.

**Comment by simon-apple** [comment]
Thanks for bringing this up! This issue has since been addressed in ResearchKit. We recommend upgrading to the latest release, which includes this fix along with many improvements and new features. If you encounter any issues after upgrading, feel free to open a new issue. Thanks for your support and for contributing to ResearchKit!
