### ISSUE TITLE
[iPad] Memory game layout jitter

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#147]
The memory game active task vertical layout is not "stable" on the iPad, either during normal usage or during rotation. Layout constraints need adjustment.

**Comment by rsanchezsaez** [comment]
In addition to one iPad specific issue with an empty header, the jitter also happens when the number of lines in the header varies between steps (the `gameView` tries to take the maximum available space).

So this would also affect *iPhones* when the localization makes the text shorter or longer.

What is the preferred behavior for accommodating different number of lines on the headers without making it jitter? Should we specify a fixed size to the game area (say, one that allows three lines maximum on the header)?

![ios simulator screen shot 8 may 2015 22 52 41](https://cloud.githubusercontent.com/assets/444313/7546380/00f92fca-f5d5-11e4-9b39-2cebc81d32f0.png)

![ios simulator screen shot 8 may 2015 22 50 25](https://cloud.githubusercontent.com/assets/444313/7546365/d4ad91a4-f5d4-11e4-968f-7c09c2fb4aa6.png)

**Comment by jwe-apple** [comment]
In principle yes, but ideally the iPhone 6 layout for the default 2-line case should not change with whatever change you make.

**Comment by rsanchezsaez** [comment]
So then: a fixed size allowing two lines maximum in the header on *iPhone 6*?

**Comment by jwe-apple** [comment]
How about if you go past 2 lines, the screen scrolls. So a fixed size on the play area, but the text can expand.

**Comment by jwe-apple** [comment]
(remember, this is all inside a scrollview)

**Comment by rsanchezsaez** [comment]
Oh yes, good point. I'll do that.

**Comment by jwe-apple** [comment]
Also - minimum height for the text area of course so there's no jitter between 0<->1<->2 lines

**Comment by rsanchezsaez** [comment]
Yup.

**Comment by rsanchezsaez** [comment]
I ended up doing a much simpler fix, and just adjusted the `ORKScreenMetricMinimumStepHeaderHeightForMemoryGame` iPad value to avoid the jitter.

---

The possible iPhone jitter if localizations go to 3 or more lines in some of the step headers remains.

It turns out that giving a fixed height to the game view and just enabling scrolling when the header has 3 or more lines would not fix the jitter either: the initial position of the game view in a 3-lined header screen with enabled scrolling would be lower than in a 2-lined header one.

Two possible solutions come to mind:
- Manually make sure that no localization has a 3-lined header.
- At the first step of game, go over all the possible step headers, compute the maximum header height, and set this as the minimum header height during all the game. This is tricky because some headers have subtitle and some others don't. If you want me to do this, let me know and I'll have a look.

**Comment by jwe-apple** [comment]
We already do the first one - and can review when it breaks.

**Comment by rsanchezsaez** [comment]
Great!
