### ISSUE TITLE
Can ResearchKit be added as via Swift Package Manager

### ISSUE THREAD

**Issue by mustafa-boorenie** [ResearchKit/ResearchKit#1507]
I recently tried to add ResearchKit to my Xcode project as a Package dependency, however, it failed. I was wondering what needed to be done to make this possible?

Thank you in advance and I hope to hear from you soon!!

**Comment by Pariecemckinney-apple** [comment]
Hello @mustafa-boorenie,

This currently isn't possible because ResearchKit doesn't support SPM.

**Comment by PSchmiedmayer** [comment]
Hi everyone,

I just wanted to share that we created a fork of the ResearchKit project over at https://github.com/StanfordBDHG/ResearchKit that supports the Swift Package Manager. 

You can import it into your project or add it to your Swift Package by following the article about [Adding Package Dependencies to Your App](https://developer.apple.com/documentation/xcode/adding-package-dependencies-to-your-app) using the following repository URL: `https://github.com/StanfordBDHG/ResearchKit`. 

While this is not an official SPM support by Apple, it might help you with your projects.

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we’ve published new versions of ResearchKit to main and haven’t seen more info posted here. PSchmiedmayer'c comment gives an alternate way to install via  Swift Package Manager. We will close this issue, however if you see this again, feel free to re-open it.
