### ISSUE TITLE
Attach Context to Surveys and Questionnaire Response Options

### ISSUE THREAD

**Issue by PSchmiedmayer** [ResearchKit/ResearchKit#1524]
Dear ResearchKit team,

We are using ResearchKit in the [ResearchKitOnFHIR](https://github.com/CardinalKit/ResearchKitOnFHIR) project to translate FHIR questionnaires into ResearchKit surveys.

In this process, we have been struggling with attaching additional context to responses. This includes the use case of FHIR value sets to define how answers are interpreted in a standardized format independent of the UI display and how they are associated with numerical values to, e.g., calculate scores based on questionnaire responses. We currently try to encode these value sets in the ORKTextChoice ([`QuestionnaireItem+ResearchKit.swift`](https://github.com/CardinalKit/ResearchKitOnFHIR/blob/main/Sources/ResearchKitOnFHIR/FHIRToResearchKit/QuestionnaireItem%2BResearchKit.swift#L200)) and then extract them to the best of our knowledge with the coding system: [`ORKTaskResult+FHIR.swift`](https://github.com/CardinalKit/ResearchKitOnFHIR/blob/main/Sources/ResearchKitOnFHIR/ResearchKitToFHIR/ORKTaskResult%2BFHIR.swift#L112).

What would be the most elegant usage of attaching the context to answers? One thing we have considered is encoding the ValueSet into a `Data` instance or encoded as a JSON value and attaching it as a context to the answer options. We would love to get your input on this approach. In general, we would argue that attaching a larger context to surveys would be valuable to keep the context within ResearchKit and easily extract it when extracting a survey response. It would be very cool to have a more Swift-native approach for this problem, e.g. a generic Coddle type that could be encoded in the context of answer options or can be attached to a survey. We are happy to hear your thoughts on this and what would be the best way to achieve this goal from your perspective. We would also like to use this additional context to, e.g., automatically calculate scores for surveys we process. It would be great if this calculation could be done right on the device without the need to further process the survey results.

Thank you for your help and support in maintaining the project!

CC @vishnuravi

**Comment by PSchmiedmayer** [comment]
We have tried to address this issue by introducing a `ValueCoding` type in the [StanfordBDHG/ResearchKitOnFHIR](https://github.com/StanfordBDHG/ResearchKitOnFHIR) project:
[StanfordBDHG/ResearchKitOnFHIR - ValueCoding.swift](https://github.com/StanfordBDHG/ResearchKitOnFHIR/blob/main/Sources/ResearchKitOnFHIR/ValueCoding/ValueCoding.swift)

We use the type (encoded as a `String`) to provide context to an `ORKTextChoice `: [StanfordBDHG/ResearchKitOnFHIR - QuestionnaireItem+ResearchKit.swift#L199](https://github.com/StanfordBDHG/ResearchKitOnFHIR/blob/main/Sources/ResearchKitOnFHIR/FHIRToResearchKit/QuestionnaireItem+ResearchKit.swift#L199)

That approach uses the `Codable`-based approach that we have discussed above. Let us know what your thoughts are and thanks for your input!

**Comment by louie-apple** [comment]
Thanks for sharing this issue! In your code example, you wrote a struct called `ValueCoding` and use it like this: `let choice = ORKTextChoice(text: display, value: valueCoding.rawValue as NSSecureCoding & NSCopying & NSObjectProtocol)`

However, if you simply write your `ValueCoding` class to conform to these protocols:

`class ValueCoding: NSObject, NSSecureCoding, NSCopying`

you will be able to to pass your class in directly as the value, instead of using the rawValue.

For example:

`let choice = ORKTextChoice(text: "whooo", value: ValueCoding(rawValue: "a word"))`

However, if adopting those protocols in your class isn't feasible -- you can also subclass the `ORKTextChoiceAnswerForma`t and override the `override func result(withIdentifier identifier: String, answer: Any) -> ORKQuestionResult` method, to write the results in a manner in which you can parse.

Please let us know if you have any other questions!

**Comment by louie-apple** [comment]
Thank you for raising this issue. Since this issue was raised, we've published new versions of ResearchKit to main and haven't seen more info posted here. We will close this issue, however if you see this again, feel free to re-open it.
