### ISSUE TITLE
Error in ORKCatalog Sample related to Saving Tasks??

### ISSUE THREAD

**Issue by cmetts** [ResearchKit/ResearchKit#1540]
I cannot get TaskViewController to present the "Save" button when the "Cancel" button is pressed mid-survey.
This is a major issue for me, which I first reported about a year ago, and again a month ago. I have no responses from either, which is surprising to me since this seems like necessary functionality in most cases to me. I am surprised others aren't having issues. 

I can reproduce the error in ResearchKit's ORKCatalog project as outlined below:

1 - Download latest stable release of ResearchKit

2- open research kit project, and compile

3- copy the research kit project file into ORKCatalog sample project

4- Modify TaskViewController swift file by adding the following:

func taskViewControllerSupportsSaveAndRestore(_ taskViewController: ORKTaskViewController) -> Bool {
      return true
}

Run ANY of the surveys or single interactions.

Click 'Cancel' top right

You are NEVER given the opportunity to save a task even though the delegate method is called repeatedly and returns true.

What am I missing here? Thanks so much for reading.

**Comment by simon-apple** [comment]
Thanks for bringing this up! This issue has since been addressed in ResearchKit. We recommend upgrading to the latest release, which includes this fix along with many improvements and new features. If you encounter any issues after upgrading, feel free to open a new issue. Thanks for your support and for contributing to ResearchKit!
