### ISSUE TITLE
Add Privacy Manifest

### ISSUE THREAD

**Issue by SwiftNativeDeveloper** [ResearchKit/ResearchKit#1567]
With the deadline for apps implementing privacy manifests right around the corner, it is important for third party SDKs to provide a manifest for app developers.

Please implement the privacy manifest for ResearchKit.

I'm tracking down why a product I'm building received the following usage warnings:
- NSPrivacyAccessedAPICategoryFileTimestamp
- NSPrivacyAccessedAPICategoryDiskSpace
- NSPrivacyAccessedAPICategorySystemBootTime

It very well could be another third party library like Firebase or the like that caused it but just doing my rounds to get all dependencies to document their required usage API reasons.

**Comment by louie-apple** [comment]
Hi @SwiftNativeDeveloper 
We recently pushed a new release, 2.2.16 (https://github.com/ResearchKit/ResearchKit/releases/tag/2.2.16) on stable. Would you please pull this release and see if it resolves your issue?

**Comment by simon-apple** [comment]
Thanks for bringing this up! This issue has since been addressed in ResearchKit. We recommend upgrading to the latest release, which includes this fix along with many improvements and new features. If you encounter any issues after upgrading, feel free to open a new issue. Thanks for your support and for contributing to ResearchKit!
