### ISSUE TITLE
No such module "ResearchKitUI"

### ISSUE THREAD

**Issue by dharaspatel** [ResearchKit/ResearchKit#1577]
I'm creating a `UIViewControllerRepresentable` so that I can use `ResearchKit` in SwiftUI. Please see my code below. It forces me to `import ResearchKitUI` Please help! I've been struggling forever and there is nothing about `ResearchKitUI` online.

<img width="1162" alt="image" src="https://github.com/ResearchKit/ResearchKit/assets/42981116/ae8cf223-085b-4b57-8904-7b1fc281786f">

<img width="1482" alt="image" src="https://github.com/ResearchKit/ResearchKit/assets/42981116/e2af063b-0863-4a0c-848a-8f57db501f13">

**Comment by Pariecemckinney-apple** [comment]
Hello @dharaspatel, happy to help here. 

In the recent 3.0 Release (https://github.com/ResearchKit/ResearchKit/releases/tag/3.0) ResearchKit was broken up into 3 modules:
- **ResearchKit**: Contains core classes that could be used in any environment.
- **ResearchKitUI**: Contains UI classes needed to present ResearchKit views.
- **ResearchKitActiveTask**: Contains the classes and objects needed to present Active Tasks in an IOS environment

The class you're attempting to access here (`ORKTaskViewControlller`) and the views it uses under the hood are all contained within the **ResearchKitUI** module. This means you do have to import **ResearchKitUI** in order to move forward which is expected now.

Hope this helps, and if you still have any issues at all please feel free to let me know!

**Comment by dharaspatel** [comment]
Ahh yes looking back that makes a lot of sense. Thanks!
