### ISSUE TITLE
[iPad] Poor performance during consent transitions

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#177]
The consent animated transitions are a bit slow (observed frame drops on an iPad Air). Need to profile and find out why. If we need to disable the tinting of these animations on iPad, then we should do so and document it.

**Comment by jwe-apple** [comment]
@rsanchezsaez Could you take a look at this one perhaps?

**Comment by rsanchezsaez** [comment]
I'll have a look.

Wouldn't be a shame to disable animation tinting on iPad? It looks greats on the study apps.

**Comment by rsanchezsaez** [comment]
Fixed in referenced pull request.

**Comment by rsanchezsaez** [comment]
It turns out this issue was not fixed at all, so please reopen.

What caused the apparent performance gains when using the custom `ORKImageByTintingImage()` function was a bug in my code that caused all consent images to be rendered at a scale of `1.0` (instead of the retina scale of `2.0`).

[PR #212](https://github.com/ResearchKit/ResearchKit/pull/212) reverts the `ORKImageByTintingImage()` change for tinted consent images.

---

I'll be trying another approach: preload the image of the next consent step when you finish arriving at a consent step. I'm pretty sure that'll fix the iPad performance issue.

**Comment by jwe-apple** [comment]
This is a lot less bad than it used to be, but there is indeed still some lag.
