### ISSUE TITLE
ORKRecorderConfiguration and ORKRecorder should have an identifier 

### ISSUE THREAD

**Issue by YuanZhu-apple** [ResearchKit/ResearchKit#2]
The aim is to let recorder generated result object has a meaningful identifier which can be used to link back to the `ORKRecorderConfiguration` object.

* The identifier will be passed from `ORKRecorderConfiguration` to `ORKRecorder`.
* The identifier is like `ORKStep` identifier which is supplied by developer.

**Comment by rsanchezsaez** [comment]
Hi guys,

I was going to implement this but I have some questions. Could you clarify this issue?

Currently `ORKRecorder` assigns its `ORKStep` `identifier` to the `ORKFileResult` `identifier`.

Do you need a new (independent from `ORKStep`) `identifier` property in `ORKRecorderConfiguration` and `ORKRecorder` that would override the `ORKStep` `identifier` on the `ORKFileResult`? Or would you rather add a property like `recorderIdentifier` to the `ORKFileResult` class so both the `ORKStep` and the `ORKRecorderConfiguration` links are preserved?

Thanks.

**Comment by jwe-apple** [comment]
The ORKFileResult generated by a recorder should have the identifier of the recorder that generated it. The current implementation happens only because there is no per-recorder identifier.
The ORKFileResult is always reported as a child of an ORKStepResult, so there is no loss of information, similar to how ORKStepResult does not include ORKTaskResult's identifier.

ORKRecorderConfiguration definitely will need an identifier property, and appropriate changes to initializers, since it will be a readonly property to match behavior elsewhere.

If doing this, make sure you run the ORKTest app and ensure the serialization tests pass after you do. You'll likely need to add an entry for the new property in the ORKESerialization implementation, following the pattern of what's there already.

**Comment by rsanchezsaez** [comment]
Cool, all is clear. Will do this shortly.

**Comment by rsanchezsaez** [comment]
I'm making good progress on this: almost everything done. I'm ready to test serialization.

By `ORKTest` do you mean the *XCTest ResearchKitTests*? I cannot find anything with a name similar to `ORKESerialization`. The `ORKResultTests` file has some keyed archiving serialization tests, but the `ORKRecorderTests` file doesn't seem to.

**Comment by jwe-apple** [comment]
No, there is an ORKTest test project in the repo. Look under testing, I think.

**Comment by rsanchezsaez** [comment]
Oh, found it. I didn't realize there was an additional project file. Cheers!

**Comment by rsanchezsaez** [comment]
Done. ;)
