### ISSUE TITLE
Auto layout warnings

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#202]
I've not seen any actually failed layout, but I'm getting auto layout spew on the console in forms in ORKTest.

Definitely a regression.

**Comment by brucehappy** [comment]
I think the spew may be due to ImageCapture.  It wasn't setting `self.translatesAutoresizingMaskIntoConstraints` to NO in its two views nor was it doing it on the subviews during `init` (before `updateContraints`).  I've updated #180 with a commit for this.  Can you check if that was the cause?

**Comment by jwe-apple** [comment]
I'm seeing it mostly in forms, actually

**Comment by jwe-apple** [comment]
@rsanchezsaez Assigning to you as you've been making the auto layout changes. Sorry if it's not you!

**Comment by jwe-apple** [comment]
Still happening.

**Comment by rsanchezsaez** [comment]
Could you provide steps to reproduce? I tried `ORKTest`'s *miniform* on iPhone 6 and iPad 4th gen. and was not able to reproduce.

**Comment by jwe-apple** [comment]
ORKTest, iPhone 6, iOS 8.3, Mini forms step 3. Scroll.

If you can't reproduce, I'll take a look tomorrow or at the weekend.

**Comment by brucehappy** [comment]
I have only been able to get a layout error message (and failed layout) from the vertical scale slider, and only on orientation change.  I have checked, and my original branch https://github.com/brucehappy/ResearchKit/tree/issue_4 does not show the issue, so this is a regression.  Here's the message:
```
2015-05-22 04:03:43.402 ORKTest[28041:588120] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x7fdbcceb3970 H:|-(51)-[ORKScaleSlider:0x7fdbcce852a0]   (Names: '|':ORKScaleSliderView:0x7fdbcce85140 )>",
    "<NSLayoutConstraint:0x7fdbcceb3ab0 H:[ORKScaleSlider:0x7fdbcce852a0]-(51)-|   (Names: '|':ORKScaleSliderView:0x7fdbcce85140 )>",
    "<NSLayoutConstraint:0x7fdbcceb6a50 H:|-(0)-[ORKScaleSliderView:0x7fdbcce85140]   (Names: '|':UITableViewCellContentView:0x7fdbcceb0150 )>",
    "<NSLayoutConstraint:0x7fdbcceb7420 H:[ORKScaleSliderView:0x7fdbcce85140]-(0)-|   (Names: '|':UITableViewCellContentView:0x7fdbcceb0150 )>",
    "<NSLayoutConstraint:0x7fdbcce87fa0 'UIView-Encapsulated-Layout-Width' H:[UITableViewCellContentView:0x7fdbcceb0150(83)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7fdbcceb3ab0 H:[ORKScaleSlider:0x7fdbcce852a0]-(51)-|   (Names: '|':ORKScaleSliderView:0x7fdbcce85140 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```
And here's a demo (you can see the message printed to my output during the final orientation change):
![verticalscalesliderlayoutissue](https://cloud.githubusercontent.com/assets/5296062/7766637/3da9fcf6-0039-11e5-851d-64dadab8d4de.gif)

**Comment by rsanchezsaez** [comment]
Hey @brucehappy, thanks for the detailed report, it was really helpful for debugging the problem. I have provided a fix in the linked pull request.

Since we were using `ORKScreenMetricVerticalScaleHorizontalMargin` to dictate a vertical scale height which avoided scrolling on *iPhone 5s* and up, I figured it'd be simpler to just supply a `ORKScreenMetricVerticalScaleHeight` metric instead. I'm using that as the vertical scale *intrinsic size*, which allows to remove the two-layered layout delegate for getting the vertical scale height.

Maybe this is a bit less general, but I think it's simpler as layout code is more self-contained. Do you think it's a good solution?

**Comment by brucehappy** [comment]
Well, its definitely simpler, but as you say, it is less general.

Personally, I'd prefer if we determined what changed between my branch https://github.com/brucehappy/ResearchKit/tree/issue_4 and master that has caused this regression, but I have not had the time to do so this past week, nor does it look like I will have the time to do so in the next few days.

So, given @jwe-apple 's 1.1 convergence effort, perhaps this is the best approach for now, and then the width derived height autolayout can get fixed later, if desired.

**Comment by rsanchezsaez** [comment]
The thing is that I don't see any particular benefits in making the *height* of the vertical scale to depend on the *width* of its container view. The width could be very large, but maybe a less tall vertical scale is desired.

It feels as if the height should be a separate metric (specially since we were having `ORKScreenMetricVerticalScaleHorizontalMargin`, which was an indirect way of setting the vertical scale height and thus fragile).

Maybe we should just make the height of the vertical scale an `ORKScaleView` property configurable by the developer?

**Comment by jwe-apple** [comment]
I don't think we want to extend it to the developer. A metric feels right to me.

**Comment by rsanchezsaez** [comment]
Fair enough.
