### ISSUE TITLE
Warnings and crash in ORKVisualConsentStepViewController

### ISSUE THREAD

**Issue by p2** [ResearchKit/ResearchKit#208]
After upgrading to latest master, when going through consenting I get a lot of these warnings:

```
<Error>: CGContextSetBlendMode: invalid context 0x0. This is a serious error. This
application, or a library it uses, is using an invalid context  and is thereby contributing
to an overall degradation of system stability and reliability. This notice is a courtesy:
please fix this problem. It will become a fatal error in an upcoming update.
```

I also noticed that the movies presented during consenting are not always tinted.

Finally, when consenting is done, I get a `EXC_BAD_ACCESS` on line 386 in `ORKVisualConsentStepViewController`: 
https://github.com/ResearchKit/ResearchKit/blob/0736e68/ResearchKit/Consent/ORKVisualConsentStepViewController.m#L386

The debugger tells me that both _weakSelf_ and _strongSelf_ are nil at that time. Reverting to 1b0d93e fixes the problem.

**Comment by rsanchezsaez** [comment]
This was my change, I'll look into it.

Is this in `ORKTest`, `ORKCatalog`, or in any of the apps? Which device and iOS version?

Thanks

**Comment by p2** [comment]
I'm using it via AppCore in my own app. You can possibly reproduce if you clone GlucoSuccess or any of the AppCore apps, update ResearchKit and go through consenting. I get the crash right when tapping whether I want to share with researchers worldwide or just the study people.

**Comment by jwe-apple** [comment]
@rsanchezsaez In general the animation layout is also broken when after rotating landscape->portrait or portrait->landscape. Try doing a rotation and then performing an animated transition. I was going to look at it, but since you're on it, can we fix that at the same time?

**Comment by rsanchezsaez** [comment]
@jwe-apple: Ok, I will look into the rotation issue.

While investigating this, I found a related issue in which the `tintColor` is set after the tinted image has been calculated. Do you know why `ORKVerticalContainerView` (which `ORKConsentSceneView` inherits from) doesn't use `ORKTintedImageView` instead of a regular `UIImageView`? I think using the tinted image view can fix this issue (while maintaining the *iPad* performance gains).

**Comment by jwe-apple** [comment]
Historical reasons. Change it!

**Comment by rsanchezsaez** [comment]
Historical raisins, haha.

Also, I suggest we add `[[UIView appearance] setTintColor:[UIColor redColor]]` or similar to `ORKTest`'s `AppDelegate`, so the *UI reviews* are done with a non-default *tintColor*. This would catch some instances where the default tint color works but a custom one doesn't (as mentioned above). Should I change this as well?

**Comment by jwe-apple** [comment]
Please don't. Feel free to do it while testing or to add a button to toggle it.

The ORKTest app is used for localization and for UI review and when we had that before it caused confusion!

**Comment by rsanchezsaez** [comment]
Ok!

**Comment by rsanchezsaez** [comment]
> While investigating this, I found an issue in which the tintColor of consent images is not set because the UIImageView has not been added to the hierarchy yet when the tinted image is calculated.

I think this issue also affects `ORKTintedImageView` if using an animated image. The problem is that `UIImageView`'s `contentScaleFactor` and `tintColor` are wrong if the image view has not been added to the main *screen* view hierarchy, and often the image of an `ORKTintedImageView` is set in advance.

I think I can fix it, I'll look into it.

**Comment by jwe-apple** [comment]
Ah, interesting.
