### ISSUE TITLE
flipToPreviousPage removes steps and results

### ISSUE THREAD

**Issue by brenbob** [ResearchKit/ResearchKit#296]
My task has a set of survey steps inserted dynamically via stepAfterStep and stepBeforeStep, and uses ORKTaskResult to consolidate results at various times in the user session. 

I've just noticed these dynamic step results are removed from ORKTaskResult when the user flips back to a previous step. Can someone explain why steps (and corresponding results) are removed from the managed arrays?

- (IBAction)flipToPreviousPageFrom:(ORKStepViewController *)fromController {
    if (fromController != _currentStepViewController) {
        return;
    }
    
    ORKStep *step = [self prevStep];
    ORKStepViewController *stepViewController = nil;
    
    if ([self shouldPresentStep:step]) {
        ORKStep *currentStep = _currentStepViewController.step;
        NSString *itemId = currentStep.identifier;
        
        stepViewController = [self viewControllerForStep:step];
        
        if (stepViewController) {
            // Remove the identifier from the list
            assert([itemId isEqualToString:[_managedStepIdentifiers lastObject]]);
            [_managedStepIdentifiers removeLastObject];

            [self showViewController:stepViewController goForward:NO animated:YES];
        }
        
    }
}

**Comment by brenbob** [comment]
Perhaps more accurately - the steps are removed from _managedStepIdentifiers. Results remain in _managedResults, but I don't see any means to access them once the corresponding step was removed.

**Comment by YuanZhu-apple** [comment]
Because ORKTaskResult stores up to date step results in a linear sequence, not all the answer history.

If you want to capture the results at various times, you can either implement:
`- (void)taskViewController:(ORKTaskViewController *)taskViewController didChangeResult:(ORKTaskResult *)result;
` to capture all result changes
or
`- (BOOL)taskViewController:(ORKTaskViewController *)taskViewController shouldPresentStep:(ORKStep *)step` to save step result before step jump.

**Comment by YuanZhu-apple** [comment]
@brenbob Please close this issue, if it has been resolved by my answer.
