### ISSUE TITLE
More media capture styles

### ISSUE THREAD

**Issue by umerkhan-apple** [ResearchKit/ResearchKit#321]
Currently there is only support for camera image capture. We want to add support for video capture and picking from media library.  Possibly add style configuration to a `ORKMediaStep`.

Would there be any specific use cases or features that should be implemented within these?

**Comment by directvox** [comment]
One of the use case that I have is to ask a question and add a note after the video has been recorded such as "Is this video representative?" .  The note can be a text input or voice recording. I hope this could help.  For us it a core feature.

**Comment by jwe-apple** [comment]
So this is media playback inline in a content area, together with effectively a single question (a la ORKQuestionStep)?

**Comment by directvox** [comment]
The way I see it is that we are requesting user to do video recording
in ORKMediaStep
so as the user, you can record it (or pick one already done in the photo
album).  Then after the recording is done, you can optionally play it again
and answer questions about it  Since RK have ORKQuestionStep I will be
better to just chain it with another step.

It will be interesting to have the possibility in ORKMediaStep to limit
recording time with a timer and a sound to notify user that the limit is
reach.  The use case for that is asking a patient to record itself for 10
minutes.

I hope you find my comments useful.

2015-08-05 23:08 GMT-04:00 jwe-apple <notifications@github.com>:

> So this is media playback inline in a content area, together with
> effectively a single question (a la ORKQuestionStep)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ResearchKit/ResearchKit/issues/321#issuecomment-128223330>
> .
>



-- 
Michel Bilodeau

**Comment by scdi** [comment]
Are we now able to record video as seen in the Autism & Beyond app?

**Comment by YuanZhu-apple** [comment]
@scdi The video recording feature is not there yet. Can you talk about your use case?

**Comment by scdi** [comment]
It would be quite similar to the comment above. We would probably have single take, no repeats, to avoid rehearsing. The goal is for analysis of emotions and sensations through artificial intelligence applications.

**Comment by directvox** [comment]
We did implement video in our RK app but unfortunately outside the RK
framework. There are many think to consider with video. For example since
video are big files, it takes time to upload it to the server. So you must
plan that the user will close the app in the middle of an upload.

If RK go ahead in creating video active task, I will add on my wish list
that converting it in mpeg4 or a different format will be nice as well as
annotate the recording with positional written comments from the user.

**Comment by YuanZhu-apple** [comment]
@scdi Do you expect it to be very similar to our existing `image capture step`? 
 - Simply let user shoot a short video and replay it before confirming it. 
 - No real time video analysis.
 - Developer obtain the video file url in result object.

**Comment by YuanZhu-apple** [comment]
@directvox Yes, the app should cache anything is pending for uploading.

Maybe you can use a `ORKWaitStep` to let user wait while you are converting video to the desired format.

**Comment by scdi** [comment]
Yes. That would work perfectly. I agree that we could simply let user shoot
a short video and replay it before confirming it. The video file url could
be obtained via file url in result object. That would be great for now.

**Comment by scdi** [comment]
At the end, is this something that we could see implemented soon?

**Comment by YuanZhu-apple** [comment]
@scdi We can try to put this into our pipeline.

**Comment by scdi** [comment]
Hi,

I am checking-in to get an update on this. Thank you for putting this in
your pipeline.
I am wondering if we have a possible time frame for its implementation.

jude

**Comment by alvaromb** [comment]
We're also interested in video recording for a very specific use-case: record different eye movement exercises. Use case would be something like:

1. Select the exercise type.
2. Record a video doing that kind of exercise with eye movement.
3. Confirm & upload the video.

@YuanZhu-apple [proposal](https://github.com/ResearchKit/ResearchKit/issues/321#issuecomment-169841547) should be enough for us.

**Comment by ninoguba** [comment]
@YuanZhu-apple can you share with us when this will be available?

**Comment by umerkhan-apple** [comment]
Video Capture has been added in RK 1.4.
