### ISSUE TITLE
Change to logName in ORKRecorder.m removes step identifier from ORKFileResult fileURL 

### ISSUE THREAD

**Issue by chrisinsfo** [ResearchKit/ResearchKit#323]
Re: Commit 49e79ab9f4df264b0085515e12658c8f61a144aa in Stable branch.

Removing the step.identifier from the logName string has removed information from the ORKFileResult fileURL. This has resulted in filenames that cannot be discriminated. For example, instead of deviceMotion_fitness.walk and deviceMotion_fitness.rest as url path components in Apple Cardiology, we now have deviceMotion_deviceMotion. 

As an example, consider ORKOrderedTask / fitnessCheckTaskWithIdentifier(). This method initializes an ORKFitnessStep and sets recorderConfigurations with an identifier such as "pedometer". When ORKRecorder returns its logName which is used to form the url, the first component is [self recorderType] which is "pedometer". The second component of the logName is now self.identifier ("pedometer"). As we can see in this example, we have less information by returning self.identifier than self.step.identifier.

@YuanZhu-apple @rsanchezsaez . Could you please comment on the intent of the change?
@DwayneJengSage @peculiar @jwarmkessel Could you please consider this issue from your perspective?

**Comment by chrisinsfo** [comment]
Further research has yielded this earlier issue: https://github.com/ResearchKit/ResearchKit/issues/2

**Comment by umerkhan-apple** [comment]
@chrisinsfo The intent of the change is to allow unique identifiers for recorders. Using the old implementation with `deviceMotion_fitness.walk`, there would be no way to identify multiple instances of a recorder of that configuration. On the other hand, with the current implementation we get `deviceMotion_uniqueRecorderIdentifer`.

![screen shot 2015-07-14 at 2 10 41 pm](https://cloud.githubusercontent.com/assets/13040996/8685229/27e0358e-2a32-11e5-915c-3b4ee3850a13.png)

I will go ahead and update `logName` to also include the step identifier, so that it would result in `deviceMotion_stepIdentifier_recorderIdentifier`. I believe this should resolve the issue you're encountering with the fileURL.

**Comment by chrisinsfo** [comment]
@umerkhan-apple . Sounds good, thanks.

**Comment by umerkhan-apple** [comment]
After internal discussion, it has been decided that it is not secure to include any identifiers in `logName` since it is used to generate filenames. Instead, the `recorderType` and the `recorderUUID` will be used to generate `logName`.
