### ISSUE TITLE
ORKResultPredicate for form step

### ISSUE THREAD

**Issue by rugheid** [ResearchKit/ResearchKit#354]
Is it possible to define navigation rules for a form step for an ORKNavigableOrderedTask? If so, how would I go about doing that?

Thanks

**Comment by jwe-apple** [comment]
What do you mean exactly? Do you want the form step itself to change? Or merely to change what the next step is based on the results of the form? You can definitely do the latter; I believe you can't do the former at present, though there has been some discussion about it.

**Comment by rugheid** [comment]
I want to change the next step based on the results of the form. Every result predicate needs a result identifier, so what to I need to fill in there? Once I have the result predicate I assume I do it as I would with a question step. I just create a navigation rule using one or more predicates and set it on the task.

Thanks for your help!

**Comment by rsanchezsaez** [comment]
@rugheid: Yeah, result predicates do work with forms: you need to pass the `ORKFormItem`'s `identifier` as the predicate `resultIdentifier`. To exemplify this I added a *form step* to `ORKTest`'s *Navigable Ordered Task* ([PR #360](https://github.com/ResearchKit/ResearchKit/pull/360)).

---

@jwe-apple: This made me realize a potential issue. Given this result hierarchy:

    taskResult
     |
     |_ stepResult
     |    |
     |    |_ questionResult
     |
     |_ formStepResult
          |
          |_ formQuestionResultA
          |
          |_ formQuestionResultB

*ResearchKit* allows `questionResult`and either `formQuestionResultA` or `formQuestionResultB` to have the same *identifier* (since they are scoped by the step identifier).

For *single-question steps*, the *questionResult* identifier is always the same as the *stepResult* identifier, but for *forms* the child *question results* get the identifiers from the *formItems*. Currently, *result predicates* only look for leaf *question results*, ignoring whether they came from *question* or *form steps*. So if you have duplicate *question result identifiers*, the predicates would match both.

The same problem arises if you have several forms on the same survey (child question results could have repeated identifiers between the different forms).

Two course of actions come to mind:
- Make sure the current predicates only match single-question steps (by also matching the *questionStepResult* identifier) and add a whole new set of methods for constructing *form result predicates*, in which you pass both the *form step identifier* and the *item identifier*. Basically, the number of public *result predicate*-building methods would duplicate. 
- Leave the code as is and document the issue in the headers (that'd place the burden on the user by recommending not to use duplicate identifiers between *form items* and *single-question steps*).

Thoughts?

**Comment by rugheid** [comment]
I would prefer making it work with possible duplicate identifiers, because I'm using duplicate identifiers in my current list. Maybe we can change the methods to use a format like "formStepResult.formQuestionResultA" as a result identifier?

**Comment by rsanchezsaez** [comment]
Sorry to bother: @jwe-apple @YuanZhu-apple, any thoughts on this?

I think the safest is to add mutually exclusive predicates for *questionResults* and *formResults*, as mentioned above. But this will duplicate the number of methods in `ORKResultPredicate`.

**Comment by YuanZhu-apple** [comment]
Thanks @rsanchezsaez !
It make sense to add mutually exclusive predicates for questionResults and formResults. Double the number of methods in ORKResultPredicate is fine.

**Comment by rsanchezsaez** [comment]
@rugheid: I have implemented this in the linked PR request. Duplicate identifiers between *form items* in different forms are no longer a problem because you must explicitly pass the `stepIdentifier` to the predicate when matching *form results*.

**Comment by rugheid** [comment]
@rsanchezsaez Thanks a lot for implementing this! It looks like a very neat solution.
