### ISSUE TITLE
Can't subclass ORKTextChoiceAnswerFormat 

### ISSUE THREAD

**Issue by brendenwest** [ResearchKit/ResearchKit#402]
I've looked at subclassing ORKTextChoiceAnswerFormat to support features not yet available in ResearchKit. For example, to add a property indicating if one choice in the list is exclusive:

    class testFormat :  ORKTextChoiceAnswerFormat {
        var exclusive : AnyObject?
        override init(style: ORKChoiceAnswerStyle, textChoices: [AnyObject]) {
            super.init(style: style, textChoices: textChoices)
        }

        required init(coder aDecoder: NSCoder) {
            super.init(coder: aDecoder)
        }
    }

This approach fails on rendering because ORKChoiceAnswerFormatHelper doesn't recognize the new class. See below. Can the helper class be updated to allow subclasses?

2015-08-26 10:20:53.417 RKtest[1720:39735] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Not a valid answerformat for this helper.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001103fac65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000110093bb7 objc_exception_throw + 45
	2   ResearchKit                         0x0000000111f84ab3 -[ORKChoiceAnswerFormatHelper initWithAnswerFormat:] + 435
	3   ResearchKit                         0x0000000111fab865 -[ORKTextChoiceCellGroup

**Comment by YuanZhu-apple** [comment]
@brenbob `ORKTextChoice` already has `exclusive` variable.

**Comment by brenbob** [comment]
Thanks. Any idea why that property is not listed in the RK docs? 

http://researchkit.org/docs/Classes/ORKTextChoice.html#

**Comment by rsanchezsaez** [comment]
@brenbob I think that's because this enhancement was added after the last official  *ResearchKit* release. Presumably it'll be added to the docs along with the next release (which should be coming quite soon).

If you want to be on the cutting-edge without waiting for new releases, to see what's new you'll have to skim over the merged *pull requests* or the *commits* on the `master` branch. ;-)

**Comment by brenbob** [comment]
I've run into a ResearchKit versioning problem with this. My local copy has the 'exclusive' property because I pulled from the master branch a few weeks ago. Now the master branch is broken and building fails with errors relating to generics and won't build. But the stable branch lacks the 'exclusive' property. 

What's the timeline for next release, or at least a build-able master branch?

**Comment by umerkhan-apple** [comment]
@brenbob The last merge into master requires you to use Xcode 7.0 or newer. The readme on Github was updated along with the last merge to reflect this change.

**Comment by brenbob** [comment]
Can the 'exclusive' ORKTextChoice feature be backported to the Stable branch? I will need this functionality before a migration to Xcode 7 becomes feasible.

**Comment by YuanZhu-apple** [comment]
@brenbob 
This is the PR contains the `exclusive` feature 
https://github.com/ResearchKit/ResearchKit/pull/205

**Comment by umerkhan-apple** [comment]
@brenbob Were you able to resolve this problem? Is it okay to close this issue?

**Comment by chrisvariety** [comment]
@umerkhan-apple 
This shouldn't be closed. This is an issue for me too. 

The lines here prevent subclassing: https://github.com/ResearchKit/ResearchKit/blob/a4c9286f2991eeb516ade75dd2ffefa0c9dd4341/ResearchKit/Common/ORKChoiceAnswerFormatHelper.m#L50-L52

I just want to add a custom initializer onto a subclass of ORKTextChoiceAnswerFormat, but am unable to do that due to the strict class checking. ResearchKit should instead check `isKindOfClass`, and is in fact already doing that, so I would propose a refactoring to something like:

```Objective-C
        if ([answerFormat isKindOfClass:[ORKValuePickerAnswerFormat class]]) {
            ORKValuePickerAnswerFormat *vpaf = (ORKValuePickerAnswerFormat *)answerFormat;
            ORKTextChoice *nullChocie = [ORKTextChoice choiceWithText:ORKLocalizedString(@"NULL_ANSWER", nil) value:ORKNullAnswerValue()];
            _choices = [@[nullChocie] arrayByAddingObjectsFromArray:vpaf.textChoices];
            _isValuePicker = YES;
        } else if ([answerFormat isKindOfClass:[ORKTextChoiceAnswerFormat class]]) {
            ORKTextChoiceAnswerFormat *textChoiceAnswerFormat = (ORKTextChoiceAnswerFormat *)answerFormat;
            _choices = textChoiceAnswerFormat.textChoices;
        } else if ([answerFormat isKindOfClass:[ORKImageChoiceAnswerFormat class]]) {
            ORKImageChoiceAnswerFormat *iaf = (ORKImageChoiceAnswerFormat *)answerFormat;
            _choices = iaf.imageChoices;
        } else {
            @throw [NSException exceptionWithName:NSGenericException reason:@"Not a valid answerformat for this helper." userInfo:nil];
        }
```

There's no real need (as far as I can tell) to have a list of `validClasses` at all. I'm happy to submit a PR if you like.

**Comment by chrisvariety** [comment]
On a separate and entirely unrelated note, the docs do not mention `exclusive` still despite 1.2 having been released a while ago. http://researchkit.org/docs/Classes/ORKTextChoiceAnswerFormat.html

**Comment by YuanZhu-apple** [comment]
@chrisvariety Thanks!

Agree with you, we could drop that strict class checking.

For the doc update, please open a separate issue.

**Comment by rsanchezsaez** [comment]
The docs have finally been updated, and I just submitted a PR solving the subclassing issue. Props to @chrisvariety for the solution.
