### ISSUE TITLE
If all fields are optional, Next field should be ungreyed

### ISSUE THREAD

**Issue by md0u80c9** [ResearchKit/ResearchKit#464]
Testable using the 'Optional Form' in ORKTest.

On page 1 of the Optional Form (tested on the simulator), there are no required items. However, the next button remains greyed.

Given that we are not required to put any information on there, it seems counterintuitive that the only way past this is to use 'skip'. If they are all optional, 'Next' is a valid response.

**Comment by md0u80c9** [comment]
Step 4 perhaps makes that clearer: Two optional fields. Because the form is 'required', there is no 'Skip'. So despite the fields being optional, you /must/ enter data into one or other of the fields.

**Comment by rsanchezsaez** [comment]
This is intentional, to clearly differentiate between the *Skip button* behavior (all results are nullified) and the *Continue button* behavior (no results are nullified).

From the [corresponding pull request](https://github.com/ResearchKit/ResearchKit/pull/443):

> Now the Continue/Done button of form steps, irregardless of them being optional, only enables if:
>
> - At least one form item has an answer.
> - All answered form items are valid.
> - All the non-optional form items have answers.

In my opinion, not enabling the *Continue button* if the form result tree would be completely empty (as it would be when using the *Skip button*) is simpler to understand and more coherent, from the user perspective. The *Continue button* button always implies that you will get some sort of valid result within the result tree (in forms and elsewhere).

This also relates to the *All answered form items needs to be valid* part: it would be weird if the *Continue button* would be enabled when no result are entered, but then disabled again if you enter one *invalid form item answer* for an *optional item*. (Also, the behavior could be confusing if we had opted to allow *invalid answers* on *optional form items*: once the user *continues*, the valid answers would get onto the result tree but the invalid ones would get nullified.)

I think that the option of adding or not adding a *Skip button* independently of *item optionality* gives maximum flexibility.

If you strongly disagree and Yuan vets the change, I could be convinced otherwise and change the behavior. But the *valid/invalid answers* part for *optional items* gets tricky. :-)

**Comment by md0u80c9** [comment]
OK - I understand the logic you used.

However, it may be a little counter-intuitive to the user to suggest you are 'skipping' a section, when you've not answered a question or questions because it's inappropriate to do so.

'Skip' suggests you are intentionally not providing the information. To me, 'Next' implies more that you have answered the section - there simply is no information to add!

It showed up particularly for me when I chose to use an optional long text icon in the last step of a questionnaire which said 'Anything else you wish to add?' Because it's the last step, Done was greyed (rather than next). Of course, having nothing extra to say is just fine, and the user would expect that they have answered that question as 'No comment'.

Does the next button get greyed if you put an invalid item in an optional field? I don't think it's unreasonable to do that if it did - but I thought at present you got an error message which prevented you proceeding. I would expect the behaviour would be that you entered invalid data into the optional item, you get the error message which prevents you moving on until you correct your data. Your alternative is to hit 'skip' which invalidates the whole section.


As an aside about invalidity, it may be preferable rather than to use the UIAlertController to change the appearance of a cell on a form to indicate it is invalid (I'm thinking a red band below it with a validation message). The main reason is for future-proofing. Let us say that functions are added to do more complex validity checking (a reasonable assumption). It is possible that if we have two form items (let's say house number and postcode as a simple albeit UK-based example: so in the UK a postcode may point to several houses, but is usually unique to a street). If you change the postcode, the house number may now become invalid (because that house number may not exist). The error is now with the house number, not the postcode (the user has just changed the postcode so we can assume the postcode is 'most' correct!). You might therefore 'flag' the house number, or both the house number and postcode as invalid.

**Comment by rsanchezsaez** [comment]
> However, it may be a little counter-intuitive to the user to suggest you are 'skipping' a section, when you've not answered a question or questions because it's inappropriate to do so.

> 'Skip' suggests you are intentionally not providing the information. To me, 'Next' implies more that you have answered the section - there simply is no information to add!

> It showed up particularly for me when I chose to use an optional long text item in the last step of a questionnaire which said 'Anything else you wish to add?' Because it's the last step, Done was greyed (rather than next). Of course, having nothing extra to say is just fine, and the user would expect that they have answered that question as 'No comment'.

But, in the  *form* use case you mention, wouldn't the idea be that you have several required items and then a last optional long text item, all within the same form? If that's the case, the user would have filled the compulsory ones on that form, and then the *Continue button* would enable. If, on the other hand, the last step is a standalone question, wouldn't it make more sense for it to be a *question step* rather than a *form?

> Does the next button get greyed if you put an invalid item in an optional field? I don't think it's unreasonable to do that if it did - but I thought at present you got an error message which prevented you proceeding. I would expect the behaviour would be that you entered invalid data into the optional item, you get the error message which prevents you moving on until you correct your data. Your alternative is to hit 'skip' which invalidates the whole section.

Yes, the button would remains disabled if there's invalid data in an optional field (in addition to the error messages), until the user corrects or deletes the data.

> As an aside about invalidity, it may be preferable rather than to use the UIAlertController to change the appearance of a cell on a form to indicate it is invalid (I'm thinking a red band below it with a validation message). The main reason is for future-proofing. Let us say that functions are added to do more complex validity checking (a reasonable assumption). It is possible that if we have two form items (let's say house number and postcode as a simple albeit UK-based example: so in the UK a postcode may point to several houses, but is usually unique to a street). If you change the postcode, the house number may now become invalid (because that house number may not exist). The error is now with the house number, not the postcode (the user has just changed the postcode so we can assume the postcode is 'most' correct!). You might therefore 'flag' the house number, or both the house number and postcode as invalid.

That is a nice suggestion. I don't like the alert views for invalid answers either (I think they interrupt the user flow). It'd be nicer to replace them by a in-cell message, along with a clear indicator that the cell answer is wrong. This may be a valid point for a new issue.

**Comment by umerkhan-apple** [comment]
@md0u80c9 I see that you have created a new issue for the in-line form item validation. Would it be okay to close this issue then?

**Comment by rsanchezsaez** [comment]
Yeah, I think this can be closed. Here's the aforementioned [Issue #467](https://github.com/ResearchKit/ResearchKit/issues/467).
