### ISSUE TITLE
ORKTaskViewController: [self managedResults] vs [_managedResults allValues]

### ISSUE THREAD

**Issue by oliverschaefer** [ResearchKit/ResearchKit#472]
`ORKTaskViewController`'s `[self managedResults]` method returns the results of all steps up to the one which is currently being displayed. If a user answers steps 1-3 and then goes back to step 2, `[self managedResults]` will only include results for steps 1 and 2, but not step 3.`[_managedResults allValues]` will include every result for steps 1-3, instead. This seems to be expected behavior (see code comments in lines 1162 and 1163). However, there should be a public way to access every available result.

**Comment by umerkhan-apple** [comment]
The purpose of managedResults is to provide answers to the questions that the user has answered. If the user answers a question and then chooses to go back to the previous step, then technically it is the same as them not answering it. Therefore, it is not viable to include a public way access all the results, because technically, we do not consider that step to be answered anymore.

Is there any specific use case where this might be a useful modification?

**Comment by oliverschaefer** [comment]
Okay, I understand the difference. I don't happen to have a specific use case yet.
