### ISSUE TITLE
Implement Activity/Motion History Retrieval?

### ISSUE THREAD

**Issue by p2** [ResearchKit/ResearchKit#491]
Is it desirable to port AppCore's [motion history reporter](https://github.com/ResearchKit/AppCore/tree/master/APCAppCore/APCAppCore/Library) classes to core ResearchKit?

Those simplify retrieval of activity history data grouped by activity type, collected by _Core Motion_. Could be enhanced by querying _HealthKit_ for step counts, flights climbed and calories burned, which we currently do in our own framework.

**Comment by YuanZhu-apple** [comment]
AppCore has a version of HealthKit data collection: https://github.com/ResearchKit/AppCore/tree/e4b158b5e234cb8e5770b980271004fa7f993bfc/APCAppCore/APCAppCore/Library/Categories/NewDataCollector/Collectors

Sure, we definitely like to have a module in RK to collect and archive HK/CM data for the apps with a friendly interface.
This data collection module should be able to collect data when the app is in the background or not running (due to memory stress or system reboot). 

Also another `data storage module` could be very useful too, which store the upload pending data.

Then developer defined upload module can use the `data storage module` to organize its uploadings.

**Comment by umerkhan-apple** [comment]
Added in RK 1.4
