### ISSUE TITLE
RestorationData prevents going backwards in Survey

### ISSUE THREAD

**Issue by md0u80c9** [ResearchKit/ResearchKit#502]
- I have an ORKNavigableOrderedTask with multiple FormSteps in.
- Start the task.
- Complete to second or third page of the form.
- Hit cancel. taskViewControllerSupportsSaveAndRestore is supported, so we 'Save for later'.
- Task is reopened using  taskViewController = ORKTaskViewController(task: StrokeNurseAdmission, restorationData: draft, delegate: self)

Result: The task opens on the page we were last working with. However, back navigation has been removed, so the last completed page is now the first available step in the navigation hierarchy.

NB I haven't managed to test whether this just applies to ORKNavigableOrderedTask or to ORKOrderedTask.

**Comment by rsanchezsaez** [comment]
This is expected behavior, as it was agreed that the ivar that the accessory that `ORKNavigableOrderedTask` uses for maintaining backwards navigation state (`_stepIdentifierStack`) was not a core part of a navigable ordered task, and as such it was nor persisted when using *NSCoding* (which is used when creating or reading restoration data).

We should improve the documentation to make this clear.

---

Or we could change course and save/restore the step identifier stack after all.

**Comment by md0u80c9** [comment]
Hi,

I guess this depends on the use case. I think the current situation may be inconsistent for users: you can go forwards and backwards through a survey, but if you 'save draft' when you return you can't go backwards.

For complex forms being able to traverse the form is very useful.

You may gather my application is looking at stroke care management: the stroke nurse form is a complex one looking at the immediate post-stroke care (to then produce a printable record and then submission to the UK Sentinel Stroke Audit) - and for them it is invaluable to be able to go back and modify their answers if need be. I can see for simpler cases this wouldn't be needed (but then again of course if it's simpler you also may not need to save work in progress at all!)

**Comment by YuanZhu-apple** [comment]
@rsanchezsaez Thanks for joining this discussion. 

`_stepIdentifierStack` is a *state* which is not normally be a part of `Model Object` (e.g. task or step). And all the states should be living on `ORKTaskViewController` and be persisted during restoration.

I talked with @jwe-apple, we would like let `ORKTaskViewController` maintain this identifier stack, and use it to provide a hint in the protocol call. It requires to change API `stepBeforeStep:` to something like `stepBeforeStep:hintStep:`. Then the `ORKTask instance` can decide how to use it.

What do you think?

**Comment by rsanchezsaez** [comment]
Actually, I just realized that `ORKNavigableOrderedTask` it's indeed persisted, so if you archive the task and unarchive it again when restoring, backwards navigation should work. @md0u80c9: I guess you are re-creating the task instead of archiving and unarchiving it?

In any case, this is clearly bad design as it causes this kind of inconsistency when re-creating the task. I'll look into improving it as Yuan suggested.

**Comment by md0u80c9** [comment]
rsanchezsaez: Yes that is correct - I'm using ResearchKit professional-side, so you may have a list of patients, each with open surveys, so we store the RestorationData as NSData in CoreData.

**Comment by rsanchezsaez** [comment]
@md0u80c9: I see, in any case, we're trying to improve the situation within the linked pull request. With that changes in the PR, it should work in your case.

**Comment by rsanchezsaez** [comment]
@md0u80c9: Did the merged PR help? If that's the case, I believe this PR can now be closed.

**Comment by md0u80c9** [comment]
Yes - looks like it has.

Sorry for not responding sooner - have been a bit tied up past few weeks! Thanks for your work on this!
