### ISSUE TITLE
ORKFormItem add convenience initialiser for optional

### ISSUE THREAD

**Issue by md0u80c9** [ResearchKit/ResearchKit#532]
Optionality is a fairly fundamental property of each ORKFormItem.

Could we consider having a convenience initialiser for it?

**Comment by md0u80c9** [comment]
I've added a pull request for it if everyone is happy that it is useful.

**Comment by YuanZhu-apple** [comment]
Optionality is a fairly fundamental property of each ORKQuestionStep too, but we didn't include it in the initializer. 

Optionality is more of an advanced feature, which is not easy for Beginners to understand. Especially involving optionality on both the step and formItem. Which make me a little hesitated.

**Comment by umerkhan-apple** [comment]
@YuanZhu-apple Since we have introduced optional on form items, I think we should include an init for it.
Especially since it is a property that by default gets set to `YES`. It is not an extra property that __can__ be set, such as  `templateImage` on `Image Capture Step`, but is automatically defined instead.

**Comment by umerkhan-apple** [comment]
#446
