### ISSUE TITLE
Adding tap duration to Tapping Task

### ISSUE THREAD

**Issue by umerkhan-apple** [ResearchKit/ResearchKit#561]
It is useful in many scenarios to also have the tap duration for the Tapping Task.

Currently, we store which button was tapped and when it was tapped.
We should also store when it was released from which the tap duration can be obtained.

**Comment by ctarda** [comment]
I would like to open a PR on this one, but since this would be my first attempt to contribute, I am not completely sure about the scope.

I assume this issue is about storing the timestamp when the button is released as a property in the sample (ORKTappingSample), and expose a property in ORKTappingSample to obtain the duration, plus tests coverage. 

Is that correct?

**Comment by m1entus** [comment]
@umerkhan-apple I will take care of it, prepare PR on couple of days

**Comment by umerkhan-apple** [comment]
Added with #654
