### ISSUE TITLE
ORKDateResult - dateFormat property would be useful

### ISSUE THREAD

**Issue by md0u80c9** [ResearchKit/ResearchKit#570]
Unlike choices, text or numeric answers, Date results cannot be managed without context at present.

If you are given an ORKDateResult, you don't know whether it is a date, a time, or a date and time without knowing what the question was.

It would be really helpful if there was another property (dateFormat or resultFormat), probably stored with an enum: ORKDateResult.Date, .Time, .DateAndTime.

**Comment by simon-apple** [comment]
Thanks for bringing this up! This issue has since been addressed in ResearchKit with the addition of the `questionType` property on `ORKQuestionResult`. We recommend upgrading to the latest release, which includes this fix along with many improvements and new features. If you encounter any issues after upgrading, feel free to open a new issue. Thanks for your support and for contributing to ResearchKit!
