### ISSUE TITLE
ORKSpatialSpanMemoryStep in Wiki = 404

### ISSUE THREAD

**Issue by Natelegreat1** [ResearchKit/ResearchKit#628]
http://researchkit.org/docs/Classes/ORKSpatialSpanMemoryStepViewController.html

The link to **ORKSpatialSpanMemoryStep** is giving me a 404...

**Comment by rsanchezsaez** [comment]
Thanks for the report.

This is due to the lack of documentation in [`ORKSpatialSpanMemoryStep.h`](https://github.com/ResearchKit/ResearchKit/blob/master/ResearchKit/ActiveTasks/ORKSpatialSpanMemoryStep.h). We should probably add some minimal documentation there. Let's keep this issue open until that is done.

**Comment by YuanZhu-apple** [comment]
Thanks @rsanchezsaez !

**Comment by rsanchezsaez** [comment]
I have fixed this as part of [Pull Request #637](https://github.com/ResearchKit/ResearchKit/pull/637).

**Comment by rsanchezsaez** [comment]
I believe this issue has been fixed by merging the aforementioned PR and can be closed.

**Comment by Natelegreat1** [comment]
Looking good!
