### ISSUE TITLE
What's the right approach to use 6-minute walk test (6MWT) in the background mode?

### ISSUE THREAD

**Issue by sharat** [ResearchKit/ResearchKit#632]
Hello All,

Looks like ResearchKit doesn't support motion sensing when the phone is in background mode. For 6MWT, it's very unlikely that the app remains in Foreground.

Even the app has background mode enabled, 6WMT doesn't collect additional steps user walked in the background mode. 

What's the right approach to solve this problem?

**Comment by YuanZhu-apple** [comment]
ORKRecorder does have background mode support: https://github.com/ResearchKit/ResearchKit/blob/7f106898e23dd00057dc08a77591913f851f6bd7/ResearchKit/ActiveTasks/ORKRecorder.m#L125-L138

When ORKRecorder starts, it start background mode for current app.

For additional information:
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplication_Class/#//apple_ref/occ/instm/UIApplication/beginBackgroundTaskWithExpirationHandler:
http://developer.radiusnetworks.com/2014/11/13/extending-background-ranging-on-ios.html

**Comment by kelseydedoshka-apple** [comment]
@sharat closing this issue as the information provided above by YuanZhu-apple is sufficient.

**Comment by Mark2xv** [comment]
Hi,

Since Apple has reduced the available time for Background Tasks to 3 minutes, where it was 10 minutes before, the 6 minute walktest will never be finished if the app is put into background as soon as the test starts. 
With iOS 13 the time will be reduced even further, down to 30 seconds.

Is this functionality still supported? If not, I would suggest removing the support for background modes altogether to prevent people wasting a few days searching for an impossible task. :)
