### ISSUE TITLE
optionally hide value in ORKSliderScaleView

### ISSUE THREAD

**Issue by dukemike** [ResearchKit/ResearchKit#657]
There are use cases where displaying the value of a scale may affect the user's response. Could a `valueLabelEnabled` attribute be added?

**Comment by YuanZhu-apple** [comment]
https://github.com/ResearchKit/ResearchKit/pull/446/ has been tried to work on this.
A quick workaround would be create a subclass of `ORKScaleAnswerFormat`/`ORKContinuousScaleAnswerFormat` to override `numberFormatter`, make formatter return an empty string for current value.

**Comment by bgannin** [comment]
I'm currently recreating #446 and updating the changes for completeness before submitting a new PR to address this ticket.

**Comment by bgannin** [comment]
FYI: there's a pull request for this now 🤞

**Comment by simon-apple** [comment]
Thanks for bringing this up! This issue has since been addressed in ResearchKit. We recommend upgrading to the latest release, which includes this fix along with many improvements and new features. If you encounter any issues after upgrading, feel free to open a new issue. Thanks for your support and for contributing to ResearchKit!
