### ISSUE TITLE
Horizontal Reference Lines

### ISSUE THREAD

**Issue by kothapas** [ResearchKit/ResearchKit#678]
Is there a way we can control where exactly the horizontal reference line is drawn? Suppose we have a goal for steps, and the reference line should be drawn at that goal, is there anyway to do that?

**Comment by YuanZhu-apple** [comment]
Assume you are talking about the chart. I don't think you have a way to control it for now.

**Comment by kothapas** [comment]
Thank you. Given that these charts are very visually appealing and could be used for other applications, I think that would be a very neat feature to consider adding.

**Comment by simon-apple** [comment]
Thanks for the feedback! The charts feature has since been removed from ResearchKit, but [Swift Charts](https://developer.apple.com/documentation/charts) can be used instead. Please feel free to open a new issue if you have any other requests or questions. Thank you again for your support of ResearchKit!
