### ISSUE TITLE
Visual consent screens should be scrollable

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#68]
Currently, scrolling is disabled on visual consent screens.

When the consent content is taller than the screen, we should allow vertical scroll (a scroll view is already present, so enabling scrolling itself will be easy).

The difficulty is that the animation between consecutive screens needs to work, and the animation itself is played in a view that is overlaid on top of the view of the VC managing the transition. When a transition is required, we should scroll to the top first, then navigate. Scrolling to the top first is only necessary for forward navigation, since animations are only applied on forward navigation and not on backward navigation in visual consent.

If you have an idea for a different work-around, happy to hear it.

**Comment by rsanchezsaez** [comment]
Initial stab at [pull request #79](https://github.com/ResearchKit/ResearchKit/pull/79).

**Comment by jwe-apple** [comment]
Seems I was a bit trigger happy on this one. A couple things need fixing:

a) The visual consent step's scroll view needs to be registered with the task view controller, so we get the hairline effect when scrolling. See the `registeredScrollView` property.

b) The video animation often goes on longer than the view controller transition. If you attempt to scroll during this period, the video animation view probably needs to scroll too, tracking the position of the scroll view.

**Comment by jwe-apple** [comment]
I would revert the change, but since you deleted your branch already let's just carry on from here.

**Comment by rsanchezsaez** [comment]
Regarding *b)*, scrolling is currently disabled until the video animation finishes. Scrolling is enabled at the same time as the back button is updated (notice how the back button on the second consent screen doesn't appear until the video animation finishes).

Do you prefer scrolling to be enabled while the video animation has not finished yet (with video view tracking, etc.)? If yes, should we advance updating of the back button to the same place?

**Comment by jwe-apple** [comment]
Regarding *b)*, in my testing I observed scrolling being enabled when the animation view was still visible, so there must be a bug here.

I also (once) got stuck with scrolling disabled, but haven't been able to reproduce again to isolate the issue.

Let's try just making the animation view track the content offset, and see how we go.

I'd prefer not to change the back button behaviour, since that has been through QA.

**Comment by rsanchezsaez** [comment]
Regarding *b)*, you were right, there was a bug. If you went back to a previous scene, when you forward to the next scene again the scroll remains unlocked even when the animation video is still playing.

I tried doing the nicest thing: not locking the scroll at all and have the animation view track the scroll position. The results can be seen in my [rsanchezsaez-visualconsentscroll-b](https://github.com/rsanchezsaez/ResearchKit/tree/rsanchezsaez-visualconsentscroll-b) branch. The problem here is that if the user scrolls before the animation video finishes, the animation freezes during scroll. I believe this is due to the `CADisplayLink` that drives the animation not firing when the user is scrolling (which I guess it's intentional so scrolling is smooth above anything else). I assume keeping the video animation playing while scrolling is not a good idea, so I don't think there's a proper solution in this case.

 So I went back and properly fixed the bug in branch [rsanchezsaez-visualconsentscroll](https://github.com/rsanchezsaez/ResearchKit/tree/rsanchezsaez-visualconsentscroll). Here, the scroll should be definitely disabled until the video animation finishes. Hence we avoid the issue.

If you can, have a look at both branches and tell me what you think. I'd go with the [rsanchezsaez-visualconsentscroll](https://github.com/rsanchezsaez/ResearchKit/tree/rsanchezsaez-visualconsentscroll) solution, as I think it provides the better user experience of the two.

If you can think of any workaround to have [rsanchezsaez-visualconsentscroll-b](https://github.com/rsanchezsaez/ResearchKit/tree/rsanchezsaez-visualconsentscroll-b) working correctly (scroll not interfering with video animation playback), I'll be happy to give it another go.

**Comment by jwe-apple** [comment]
For your -b patch, try adding the CADisplayLink with modes `NSRunLoopCommonModes` rather than `NSDefaultRunLoopModes` ?

**Comment by rsanchezsaez** [comment]
`NSRunLoopCommonModes` did the trick! Now the [rsanchezsaez-visualconsentscroll-b](https://github.com/rsanchezsaez/ResearchKit/tree/rsanchezsaez-visualconsentscroll-b) patch seems to work fine.

I added the `ORKScrollToTopAnimationDuration` constant to `ORKHelpers` (used by both `ORKConsentSceneView` and `ORKAnimationPlaceholderView`). Let me know if you think it should be elsewhere.

**Comment by jwe-apple** [comment]
Yeah, that's an ok place for it. Can you please submit as a pull request?

**Comment by rsanchezsaez** [comment]
Submitted [pull request #96](https://github.com/ResearchKit/ResearchKit/pull/96).

**Comment by jwe-apple** [comment]
Verified.
