### ISSUE TITLE
ORKCompletionStep checkmark auto layout issue

### ISSUE THREAD

**Issue by umerkhan-apple** [ResearchKit/ResearchKit#864]
![simulator screen shot nov 7 2016 11 44 24 am](https://cloud.githubusercontent.com/assets/13040996/20124519/df37977e-a5db-11e6-984b-6d4195e6069a.png)

**Comment by huever** [comment]
Solved this replacing **layoutSubviews** Method **ORKCompletionStepViewController.m** with

```
- (void)layoutSubviews {
    [super layoutSubviews];
    CGRect rect = CGRectMake(self.bounds.size.width, self.layer.frame.origin.y, TickViewSize, TickViewSize);
    self.layer.frame = rect;
}
```

Maybe this could help with this bug

**Comment by ninoguba** [comment]
This was addressed by #821 but @huever's fix looks much simpler.

**Comment by syoung-smallwisdom** [comment]
Duplicate of https://github.com/ResearchKit/ResearchKit/issues/820
Addressed by https://github.com/ResearchKit/ResearchKit/pull/821

I chose to address using constraints b/c while the code is longer, using constraints rather than hacking the layout does not risk reintroduction of this bug when Apple changes the rules for iOS 11. ;)

**Comment by ninoguba** [comment]
PR #831 fixes this

**Comment by kelseydedoshka-apple** [comment]
#831 has been merged and therefore fixes this issue.
