### ISSUE TITLE
Incorporate Touch ID into ResearchKit informed consent

### ISSUE THREAD

**Issue by jwe-apple** [ResearchKit/ResearchKit#88]
<rdar://problem/20177525>

Some applications may wish to establish a passcode during informed consent, and then use either that passcode or touch ID on further uses of a ResearchKit app to access certain features.

This task is to add a concept of authentication at the task or task view controller level. We will also need an authentication setup step to create a passcode during informed consent and optionally enable Touch ID. 

For reference UI, look at how Touch ID is set up during initial setup of an iPhone.
For reference code, it may be helpful to look at AppCore, e.g. `APCKeychainStore` and `APCChangePasscodeViewController`, but the details of a ResearchKit implementation are likely to be quite different.

**Comment by getaaron** [comment]
Would you want ResearchKit to write a passcode to the keychain? Or should that be an exercise for the developer?

**Comment by jwe-apple** [comment]
Yes, there should be a ObjC wrapper in ResearchKit which writes the passcode to the keychain, similar in principle to `APCKeychainStore`. This may need a concept of a study identifier.

Would like the keychain storage part to be largely independent of the rest of the framework. It should integrate well with e.g. `ORKTaskViewController`, but should not be dependent on it, if that makes sense.

**Comment by KaiCode2** [comment]
I'm about to start work on this task and to my understanding here is what I'd to do.

*  Incorporate a touchID (with passcode) as a consent step.
*  Allow tasks to require authentication via. TouchID (with passcode backup). This could be achieved either with a non-optional ORKStep (so users can't skip it) that would be placed in the front of the ORKTask or I could add a method to ORKTask protocol with something like this;
```Objective-C
- (Bool) requiresAuthentication
```
with 'No' by default.

I'd like to know if I return the authentication data back to the developer or if I store it in keychain making the authentication only available on a per device basis and thus would require the user to re-authenticate on a new device. 

Any suggestions/feedback?

**Comment by YuanZhu-apple** [comment]
Thanks for taking on this issue!

*  Incorporate a touchID (with passcode) as a consent step.
   - Yes, let user create a passcode for this app and optionally enable Touch ID.
* Allow tasks to require authentication.
   - The authentication usually happens on app level. It is uncommon to require authentication for each task. 
In my opinion, a  `ORKPasscodeViewController` would be very useful which can be presented by application to authenticate user.

**Comment by umerkhan-apple** [comment]
@KaiCode2 What is your state on this feature?

**Comment by KaiCode2** [comment]
I'm currently working on the TouchID consent viewController. I'll try to have it this done by the end of the week.

**Comment by YuanZhu-apple** [comment]
Hey @KaiCode2
Before you go too far, can you share your API design with us first? Thanks!

**Comment by umerkhan-apple** [comment]
@KaiCode2 After internal discussion, we have come up with an API design for this feature. Below is a diagram explaining what it entails. Let me know if your design matches or is close to it.

![screen shot 2015-07-21 at 5 22 18 pm](https://cloud.githubusercontent.com/assets/13040996/8815387/394e068e-2fcd-11e5-9be9-83d74cb5c9a2.png)

**Comment by KaiCode2** [comment]
@umerkhan-apple Great! My design was quite similar but I do have a question about where TouchID will be added into the diagrams listed above? 

Looking forward to working on this!

**Comment by umerkhan-apple** [comment]
@KaiCode2 The TouchID will be presented at different times for the different views. For the `Passcode Create Step View`, it will be presented after the user has entered the passcode twice--providing an option to enable TouchID. In `Passcode Entry Modal View`, it will be presented before the passcode keyboard is displayed. In `Passcode Edit Step View`, it will be presented at the beginning and then the user will be prompted to enter a new passcode. After the user has entered the passcode twice, the TouchID enable view will be displayed.

If you have made any significant progress with this feature, can you share it, so we can see how close to the API design it is? Otherwise, we would like to take on this feature due to time constraints.

**Comment by KaiCode2** [comment]
@umerkhan-apple OK, sure.

I have made quite minimal progress so far since I just started work on it within the last couple days. How soon are the time constraints? If they are under a week then feel free to assign this to someone else but I should be able to make significant progress over the weekend.

**Comment by umerkhan-apple** [comment]
@KaiCode2 Since you haven't already invested a lot of work into the feature yet, I think it will be best for us to go ahead and take it up. Thank you for your collaboration and involvement with RK!

**Comment by KaiCode2** [comment]
@umerkhan-apple OK, well let me know if anything changes, would love to finish what I started.

**Comment by KaiCode2** [comment]
@umerkhan-apple Do you mind me asking when you would've needed this by? I could most likely finish it over the weekend and have it in for review by Monday if that would speed up 1.2 for you guys.

**Comment by DanKeen** [comment]
Kai, that sounds great. Go for it!

**Comment by KaiCode2** [comment]
@DanKeen Cool, thanks :)

**Comment by umerkhan-apple** [comment]
@KaiCode2 How is the work coming along?

**Comment by KaiCode2** [comment]
@umerkhan-apple I worked on a fair bit of it throughout the weekend and have laid out the structure of the integration and am starting on most of the UI.

#### First, here's the details on how I was thinking it will.

1. Creating Passcode: I'm structuring the creation of the passcode (and TouchID) similar to how the signature is implemented for consent by having a ORKCreatePassCodeController which has a PassCodeView (either a 4-digit passcode or a strong passcode).The user will be required to enter the passcode twice and before I save that information to the KeyChain I will check if the user has TouchID capabilities. If that's the case, I'll prompt them to add that info before saving it to the local KeyChain database. (Note: I was planning on only storing the information locally and not enabling this to sync to other devices but let me know what you think about that.)

2. Authenticating Passcode: I watched the WWDC 2014 sessions on [keychain and TouchID](https://developer.apple.com/videos/wwdc/2014/#711) and the way they say to do it is to pop a system provided TouchID alert. If the user successfully enters a correct finger it'll give a call back saying it succeeded  and if the user selects 'enter passcode' it'll dismiss and I'll get a callback saying they want to enter passcode which I need to provide. At that time I'll present either a one step task with an authentication step or if the authentication step is at the end of a task then i'll present the PassCode. From there I can do a simply check with KeyChain to see if the value in the database matches and if so I'll inform the client that the user passed the authentication. 

3. Updating: This is simply going to be a step with two sub-steps in it (similar to creating a passcode). It will allow the user to enter a passcode in one step and confirm it in the next and if they match we will update the keychain with the new value.


#### The issues I've encountered as far as integrating with ResearchKit are:

* I'm trying to model the creation of a passcode similar to a signature (let me know if you think this is a good idea) and it took me a while to navigate the code to comprehend what's happening (such as to why ORKConsentSignatureController is a UIViewController).
* I'm also not totally sure what needs to be implemented in order to become a valid ORKStep or an ORKTask.

If I can get through those minor issues then I think this PR will not only go a lot faster but will also improve any future work I do for RK.


#### CheckList

I'll just throw up a checklist so that you can see how far along this is: (I'll update this throughout the PR)

- [x] clear understanding of how the new feature will be implemented.
- [x] laid out **all** foundation needed (ie: all protocols and class headers are defined)
- [ ] write **all** UI elements // IN PROGRESS
- [ ] write components to interact with KeyChain and TouchID // IN PROGRESS
- [ ] Complete all ORKTasks and ORKSteps
- [ ] Submit PR for review


Let me know if you think I'm far enough along to continue. Once I get the minor hurdles out of the way progress should be quite smooth :)

**Comment by umerkhan-apple** [comment]
@KaiCode2 Thanks for working on this!
Let me go ahead and address everything in the same order you explained them.

**Creating Passcode:**
* Refactor ORKCreatePassCodeController --> ORKCreatePasscodeStepViewController.
* Refactor ORKPassCodeView --> ORKPasscodeStepView
* The delegate can just pass back the raw input from the passcode view. There is no need to implement the keychain storage yet. That should be done in a separate PR. All the keychain storage and retrieval will be implemented then.

**Authenticating Passcode:**
* The passcode should only be associated with an app, not with a specific task. Therefore, when the callback for 'Enter Passcode' happens, you can just modally show the passcode view.

**Updating:**
* Take a look at the system's way of changing passcode. You will need a step with three sub-steps:
   - Sub-step 1 will be entering the old passcode.
   - Sub-step 2 will be entering the new passcode.
   - Sub-step 3 will be confirming the new passcode.

**Issues:**
* Follow the hierarchy of any of the steps (e.g. InstructionStep). This way you should have ORKPasscodeStep, ORKPasscodeStepViewController, and ORKPasscodeStepView.
* To find a good example of which methods to implement for a valid ORKStep, check out `ORKInstructionStep.m`.

**Comment by umerkhan-apple** [comment]
@KaiCode2 How is the PR coming along?

**Comment by chrisvariety** [comment]
Any status updates on this? Would like to use this myself. @KaiCode2

**Comment by umerkhan-apple** [comment]
Due to inactivity, I will go ahead and take on this PR for now.

**Comment by KaiCode2** [comment]
@umerkhan-apple Sincere apologies, just got home the other day from vacation. That sounds like the best course of action, best of luck.
