### ISSUE TITLE
Filling in Logically Skipped questions

### ISSUE THREAD

**Issue by wjacksonusm** [ResearchKit/ResearchKit#888]
If I'm skipping from question 1 to question 5 is there a way to fill in the results of questions 2-4 so that they appear in the results object at the end of the survey?

**Comment by dannyiss** [comment]
Do you mean fill in with a default result? What purpose would that be? Wouldn't the skipping mean you don't need answers?

**Comment by wjacksonusm** [comment]
Yes, its for reporting purposes. Basically we loop through the results and give the questions identifiers for backend reporting, but the identifiers end up not matching because of the skipped questions. If we could get the skipped questions with default or dummy data, no other changes would be needed for our backend reporting. This would be preferred since the survey reporting generates the reports dynamically for many different surveys with various question lengths. This prevents having to generate new tables for each new survey that we create in the app. I hope that helps answer your questions.

**Comment by wjacksonusm** [comment]
Thank you Andrew. We will look into this!

**Comment by md0u80c9** [comment]
Just reflecting on your question a bit - I think you might be approaching your problem wrongly.

What I think you need to do is to disable skip for those questions by setting optional to no.

Then what you need to do is to add a default answer for those questions - so in other words the user has to acknowledge that this is the answer you are going to provide on their behalf. They can 'skip' by just pressing next (because the answer is already filled in), but they have to affirm that the default answer is the one they want to give.


Clearly the earlier response does what you need if working around it is necessary - but I suspect it's a UI issue rather than a programmatic one if that makes sense.
